### ISSUE TITLE
New line after punctuation mark

### ISSUE THREAD

**Issue by sourcerer-mike** [php-fig/fig-standards#173]
### Situation

In all documents the next sentence occur after the other:
```
In this stage, major additions to the meta document are strictly prohibited. If alternative approaches are
discovered that are not yet listed in the meta document, the Coordinator must abort the Review by 
```

### Problem

If the previous sentence changes almost all following lines need to change in order to keep the maximum line width.

```
In this stage, major additions to the meta document are strictly prohibited because they this that lorem ipsum dolor
sit amet. If alternative approaches are discovered that are not yet listed in the meta document, the Coordinator
must abort the Review by [... and here comes the next line, etc... ]
```

### Solution

While writing place a new line after the end of the sentence or primarily at other punctuation marks:

```
In this stage, major additions to the meta document are strictly prohibited.
If alternative approaches are discovered that are not yet listed in the meta
document, the Coordinator must abort the Review by foo.
Next and so on. 
```

### Benefit

- This prevents you from rearranging the whole paragraph over and over again.
- Additions can be made easier and very fast.
- The markdown will still show it as a single paragraph.
- The printout of the source has space to take notes.

**Comment by michaelcullum** [comment]
Feel free to raise this on the mailing list but we are currently preparing to close issues on this repository.
