### ISSUE TITLE
[PSR-5] co-variance in generic collection-types

### ISSUE THREAD

**Issue by mindplay-dk** [php-fig/fig-standards#180]
The spec does not specify whether generic collection-types are considered invariant or covariant.

Given that this is PHP, a dynamic language, I believe covariance should be allowed, e.g.:

    abstract class Animal {}
    class Cat extends Animal {}
    class Dog extends Animal {}
    
    /**
     * @param Animal[] $animals
     */
    function feed($animals)
    {}

    /**
     * @var Cat[] $cats
     * @var Dog[] $dogs
     */
    $cats = array();
    $dogs = array();

    feed($cats);
    feed($dogs);

The latter two statements should be considered valid.

Please see [this issue](http://youtrack.jetbrains.com/issue/WI-20053) for a more detailed discussion.

**Comment by michaelcullum** [comment]
We are currently in the process of deprecating the issues on this repository. Feel free to raise your ideas on the Mailing List.
