### ISSUE TITLE
PSR-4 Definitions is missing the term Namespace

### ISSUE THREAD

**Issue by hakre** [php-fig/fig-standards#188]
I just quickly grasped over PSR-4 and left some comments to earlier commits I considered a smell. As I already found two it made me curious and I though, hmm, this all looks so file-system centric. And then indeed:

The Definitions do not say what a *Namespace* actually is. How come?

This should spare some words in section 2 and even more words in section 3.

Ref:

1. https://github.com/php-fig/fig-standards/commit/3d601f9236eb42bb467f2a3377d414248a99b690#commitcomment-4184532
2. https://github.com/php-fig/fig-standards/commit/ce35a1782563586d9f46e1bd98d2287d202c5f24#commitcomment-4184592

**Comment by michaelcullum** [comment]
I'm not really sure I see a huge amount of benefit to this change and as the spec is finalised, unless there is a good reason to change it, I'd rather leave it as-is.
