### ISSUE TITLE
[PSR-4] possible logical elaboration in psr-4-autoloader.md 

### ISSUE THREAD

**Issue by AlexYursha** [php-fig/fig-standards#196]
Clause 3.1.5 of the psr-4-autoloader.md specifies that:

> The "fully qualified class name" MUST begin with a "namespace name"...

Meanwhile the definition of the *Namespace Prefix* in the same document says:

> Given a "fully qualified class name" of Acme\Log\Formatter\LineFormatter, the 
> "namespace prefix" could be Acme\, Acme\Log\, or Acme\Log\Formatter\.

If I correctly understood that *Fully Qualified Class Name* always begins with a *Namespace Prefix*, then Clause 3.1.5. can be changed as follows:

> The "fully qualified class name" MUST begin with a "namespace prefix"...

The rationale behind this is that the term *Namespace Name* has broader sense than the term *Namespace Prefix*.

**Comment by michaelcullum** [comment]
PSR-4 is final and cannot be changed.
