### ISSUE TITLE
Missing translations for the PSR-0 title

### ISSUE THREAD

**Issue by bobthecow** [php-fig/fig-standards#203]
Google Translate and a couple of years of high school spanish (more than a decade ago) yielded the following approximations:

 * Estándar del autoloader
 * La norme de chargeur de classes
 * Standard per la autoloader

But trust me, I'm far from qualified to make this decision. Halp!

cc: @Adel-E @aferrandini @albertosarullo @corsaroquad @dosten @egulias @giorrrgio @jfcalcerrada @lesmyrmidons @MatCottet @mikaelkael @mweimerskirch @Osukaru @rittme @villamarin

_(Related: is a loan word like `autoloader` masculine or feminine? The italian and spanish translations seem to disagree)_

**Comment by michaelcullum** [comment]
This should be closed now @samdark
