### ISSUE TITLE
What is the current state of using "acronym" in Class/Method name?

### ISSUE THREAD

**Issue by rezigned** [php-fig/fig-standards#229]
If this question has been asked before, please ignore my question. I'm trying to find a documentation about "acronym" in class/method name, but I couldn't find one.

Since PSR has explicitly stated that class/method name should follow ``CamelCase`` convention. But what happened if that class contains some acronym, for example ``XML`` e.g. ``SimpleXMLElement`` (This convention was used by PHP language itself).

What should we do here?

**Comment by glen-84** [comment]
> I beleive it should be SimpleXmlElement to avoid such unreadable names as RESTAPIInterface and SQLToXMLConverter

+1
