### ISSUE TITLE
What about common collections framework?

### ISSUE THREAD

**Issue by Sharom** [php-fig/fig-standards#270]
Most of the time we can use an flat array. But some times we need to make some complicated operations with a collections and OO-style code can be much easier to use.

Another case when it is easier to use collections framework:
Try to imagine that you should to develop some API with JSON-serialization. What should you do with `array()`? Is it an array or a map (Object in context of JSON).

I think that we can take basics from interfaces from Java and adapt it for PHP.

What do you think about it?

**Comment by HallofFamer** [comment]
Check out my PHP Collections Framework(PCF) project, it is being hosted on phpclasses.org. Note it does not handle primitive types yet, but you can use the wrapper classes I provide to insert primitive values into collections: 
http://www.phpclasses.org/package/8008-PHP-Manipulate-collections-of-objects-like-Java-and-C-.html

**Comment by funivan** [comment]
Collections are useful in several cases:
* Clean and intuitive api to manage data
* Access to list only with specific objects  
`public function add(UserModel $userObject)` This code guarantee that collection contains only `UserModel` and sometimes it is very good approach  to avoid errors. 

@Sharom https://github.com/LitGroup/Collection/tree/develop - 404

**Comment by michaelcullum** [comment]
We discuss new proposals for PSRs on the mailing list first normally. If you'd like to continue with this, please suggest it on there where we can discuss it going to a potential entrance vote.

https://groups.google.com/forum/#!forum/php-fig
