### ISSUE TITLE
@deprecated and @since presuppose and enforce [<"Semantic Version">] on software

### ISSUE THREAD

**Issue by gerardroche** [php-fig/fig-standards#278]
Maybe i'm misunderstanding it.

Both of the following tags and any other tag referring to "Semantic Version" are effectively enforcing the Semantic Version Spec 2.0.0 on all software in question.

    @since [<"Semantic Version">] [<description>]
    @deprecated [<"Semantic Version">] [<description>]

**Semantic Version Definition**

> "Semantic Version" refers to the definition as set in the [Semantic Versioning Specification 2.0.0](http://semver.org/)

The Version definition should maybe be more generic and only *recommend* semver?

**Comment by michaelcullum** [comment]
We are currently in the process of deprecating the issues on this repository. Feel free to raise your ideas on the Mailing List.
