### ISSUE TITLE
Unindented ordered lists make nonsense of list numbers

### ISSUE THREAD

**Issue by jameshfisher** [php-fig/fig-standards#281]
See for example: http://www.php-fig.org/psr/psr-4/

At least in my browser (recent Chrome), the sub-lists are not indented beyond the parent lists, meaning that the user sees a flat list of bullet points like

    // 2. Specification

    1. ...
    2. ...
    1. ...
    2. ...
    3. ...
    4. ...
    5. ...
    6. ...
    3. ...

... and so on.

Viewing [the markdown source](https://raw.githubusercontent.com/php-fig/fig-standards/master/accepted/PSR-4-autoloader.md) reveals the semantic indentation that should also be present in the generated HTML/CSS.

**Comment by michaelcullum** [comment]
This appears to have been fixed.
