### ISSUE TITLE
PSR-7: StreamInterface is not limited to HTTP messages

### ISSUE THREAD

**Issue by WanWizard** [php-fig/fig-standards#293]
Just wondering why the StreamInterface is part of PSR-7.

It is a very generic interface, for which I can see a lot of potential in other contexts than HTTP messages. It will be akward to have packages implementing those "contexts" depend on a HTTP message standard, just so you can use StreamInterface. 

Not to mention the risk of HTTP message specific code that may sneak into StreamInterface in the future, breaking those packages...

Perhaps it's better to create a separate PSR for the StreamInterface, so it can be kept generic, and re-use is easier.

**Comment by weierophinney** [comment]
@dragoonis Please close; this issue is covered in both the comments and in the meta document.

**Comment by nathggns** [comment]
Regardless of this, could it not just be under `\PSR\StreamInterface` or similar? I see no reason for this to be under an HTTP namespace.

**Comment by weierophinney** [comment]
@nathggns if a PSR for streams is ever created and ratified, we'll do an addendum to PSR-7 to have it extend that interface and/or bridge it. It *does* need to be under the `Psr\Http\Message` namespace for now, however, as we're only treating those elements of streams that are required for purposes of working with HTTP message bodies.

@pmjones -- can you close this issue, please?
