### ISSUE TITLE
[PSR-7] Case Insensitive Header *Names*

### ISSUE THREAD

**Issue by cebe** [php-fig/fig-standards#349]
In https://github.com/php-fig/fig-standards/blob/master/proposed/http-message.md#case-insensitive-headers it should be made clear that not the whole header is case insensitive but the header names only. So instead of talking about Case Insensitive Headers it should be talking about Case Insensitive Header *Names*.

Further more in the following section https://github.com/php-fig/fig-standards/blob/master/proposed/http-message.md#headers-with-multiple-values there is no need to emphasize on the case insensitivity of header names, this has been defined in the section before already.

**Comment by weierophinney** [comment]
@dragoonis Please close; this was fixed with #349.

**Comment by cebe** [comment]
looks good :+1:
