### ISSUE TITLE
[PSR-7] Include support for multipart messages

### ISSUE THREAD

**Issue by jgornick** [php-fig/fig-standards#352]
I've reviewed the proposal for PSR-7 and didn't see support to build a multipart message. Maybe this doesn't fit into the scope of PSR-7?

[Guzzle implements a multipart body](https://github.com/guzzle/guzzle/tree/master/src/Post), but assumes that you are uploading a file or specifying a key/value pair. However, if I wanted to include a part that **only** contained a ```Content-Location``` header, I wouldn't be able to.

I've researched a couple of existing implementations that allow full control over the building and parsing of multipart messages:

* [Go: Package multipart](http://golang.org/pkg/mime/multipart/)
* [Mime4J: Interface Multipart](https://james.apache.org/mime4j/apidocs/org/apache/james/mime4j/dom/Multipart.html)

Thoughts?

**Comment by weierophinney** [comment]
@dragoonis This can be closed now.
