### ISSUE TITLE
[PSR-10] Raw PHP File Format

### ISSUE THREAD

**Issue by antonioribeiro** [php-fig/fig-standards#397]
**Raw PHP File Format - for Editors - PROPOSAL**

Consider creating a new PSR: Raw File Format for PHP Editors. Adopting editors would save code in this "raw format" and display it in whatever coding style the user like. People would be pleased by looking at the code using their own personal format (PSR-2, PEAR, Zend, Symfony, PSR-2-ish+Allman's), Open Source maintainers would never have to waste time with styling again, people like @GrahamCampbell will be able to focus on more important stuff, end of story.

Originally posted in https://github.com/laravel/framework/issues/6836#issuecomment-68256973

**Comment by michaelcullum** [comment]
We discuss new proposals for PSRs on the mailing list first normally. If you'd like to continue with this, please suggest it on there where we can discuss it going to a potential entrance vote.

https://groups.google.com/forum/#!forum/php-fig
