### ISSUE TITLE
[PSR-7] Method argument namings

### ISSUE THREAD

**Issue by graste** [php-fig/fig-standards#410]
Hi,

this might be nitpicking, but I really wonder why the interfaces have method signatures like ```getHeader($header)```, ```setHeader($header, $value)``` or ```getAttribute($attribute)```. The naming of arguments doesn't make sense to me as it somehow implies objects instead of a string scalar (or name). Even the ```@params``` documentation says it's a name.

I suggest changing all relevant  arguments to something slightly different. For header fields according to [rfc7230](https://tools.ietf.org/html/rfc7230#section-3.2) this might be something like ```$headerFieldName```, ```$fieldName``` or maybe even only ```$name``` with ```$value``` (when `setHeader` already implies the word `field`). The same suggestion applies to at least the `attribute` handling methods as those have attribute keys/names as well.

**Comment by weierophinney** [comment]
You can use whatever verbiage you want in your own implementations. The verbiage here is well-known, and seen in a variety of projects already.

**Comment by weierophinney** [comment]
@pmjones Please close.

**Comment by graste** [comment]
I thought it might be nice to have consistent namings that make sense upon first read and not some potentially misleading names – especially in an interface about framework *interoperability* that will be used everywhere in already existent and upcoming libraries and frameworks. It's not as if there will be another attempt at these interfaces in the near future…

**Comment by lnwdr** [comment]
> You can use whatever verbiage you want in your own implementations.

Shouldn't the interface that everybody will rely on for years to come have precise names then, leaving the "whatever verbiage you want" to implementations?

> The verbiage here is well-known, and seen in a variety of projects already.

Something being "well known" or "common sense" is not a good reason for an ambiguous interface. If everything was "well known", we wouldn't need interfaces at all.

I agree with @graste that an argument called `$header` implies an object that represents an entire HTTP header's name and value while `$headerName` (or sth similar) makes it obvious that it only refers to the name.

**Comment by weierophinney** [comment]
My point is that what is obvious to some is not obvious to others, and vice versa. No matter what we choose, _somebody_ will be unhappy with the naming. Considering the docblocks provide plenty of detail about what is expected, changing the names at this point is not critical.

If you feel strongly about it, create a pull request (please make sure you prefix it with "[PSR-7]"!), suggest the names there, and ask for feedback. I'm not going to try and guess what names will be more clear at this point; until this issue, nobody has indicated ambiguity.

**Comment by graste** [comment]
At least the two persons in this thread *indicated ambiguity*. I created a pull request with my suggested changes as *not critical at this point* is a weird assumption on interface definitions in my humble opinion. Thank you for your patience though.

**Comment by weierophinney** [comment]
> not critical at this point is a weird assumption on interface definitions

What I meant is: it doesn't change how they operate, or the expectations defined. It is changing the variable names only. After such a change, any concrete implementation will continue to work as-is. This is why I used the verbiage "not critical." It doesn't mean "not important," just that it will not change behavior.
