### ISSUE TITLE
[PSR-7] Note Turkish I problem?

### ISSUE THREAD

**Issue by TazeTSchnitzel** [php-fig/fig-standards#417]
The PSR-7 draft currently says this:

> Case-insensitive header names

> HTTP messages include case-insensitive header names. Headers are retrieved by name from classes implementing the MessageInterface interface in a case-insensitive manner. 

Perhaps for clarity, it should mention that this case-insensitivity must be according to the `us-ascii` locale, otherwise you might have issues on Turkish locale systems?

Then again, that's an implementation detail, really.

Maybe it should link to where the HTTP RFC defines case-insensitivity.

**Comment by weierophinney** [comment]
#415 already addresses this, and should be merged shortly. :)
