### ISSUE TITLE
PSR-7: no word about normalization

### ISSUE THREAD

**Issue by Tobion** [php-fig/fig-standards#426]
Currently the PSR-7 proposal does not say anything about URI normalization in their interfaces which is also discussed in https://tools.ietf.org/html/rfc3986#page-38

So for example:
- Does `getPath` return an empty string or `/` which is considered equal?
- Can the path be percent-encoded or is it always returned in decoded form?
- Are dot-segments ("." and "..") in the path resolved automatically?

And if nothing happens, then the documentation should mention that everything is returned as provided and no normalization takes place.

**Comment by Tobion** [comment]
The prototype implementation actually normalizes the empty path to `/` but the phpdoc is contradictory: https://github.com/phly/http/blob/b6475990dc7858ac40ab5eb432c598629cac16ac/src/Uri.php#L204-L207

**Comment by weierophinney** [comment]
@Tobion you're referencing phly/http, versus the spec itself, which explicitly states that getPath() should return an empty string if no path is present.

Normalization is not addressed in the specification, which means that the instance should retain all segments as provided.

**Comment by weierophinney** [comment]
@Tobion also, clearly, I need to fix my implementation in phly/http to comply. :)

**Comment by Tobion** [comment]
So does `getPath` return `''` for both `http://example.org` and `http://example.org/`?
If so, it would apply normalization. And this normalization would only apply for http scheme. So I feel it's inconsistent to apply only some normalization. I guess it would be better to do no normalization at all and leave that to another library when needed.

> For example,
   because the "http" scheme makes use of an authority component, has a
   default port of "80", and defines an empty path to be equivalent to
   "/", the following four URIs are equivalent:

https://tools.ietf.org/html/rfc3986#section-6.2.3

**Comment by Tobion** [comment]
Since the UriInterface explicitly states

> This interface is meant to represent only URIs for use with HTTP requests,
 * and is not intended as a general-purpose URI implementation.

we have two options IMO:

1. no normalization since dot-segment are probably not normalized as well; so getPath for `http://example.org` -> `''` and `http://example.org/` -> '/'
2. only normalize the path according to http://tools.ietf.org/html/rfc7230#section-2.7.3 
this would mean `/` should be returned for `http://example.org`

> an empty
   path component is equivalent to an absolute path of "/", so the
   normal form is to provide a path of "/" instead.

**Comment by weierophinney** [comment]
@Tobion The spec says clearly:

> if no path is present it MUST return an empty string

What this means is: PSR-7 does not specify any normalization. Thus:

- `getPath()` for `http://example.org/` returns `/`.
- `getPath()` for `http://example.org` returns an empty string.

What I'm unsure of is whether you think this is acceptable, or if you suggest we change the spec to return `/` when no path is specified (per section 6.2.3). Can you please clarify?

> Can the path be percent-encoded or is it always returned in decoded form?

The path can be percent-encoded, and #449 clarifies this. `withPath()` and `withQuery()` will be expected to percent-encode any reserved characters, but will also be expected to prevent any double-encoding. Paths and query strings returned will be returned as set (with the exception of percent-encoding as specified).

> Are dot-segments ("." and "..") in the path resolved automatically?

No. That can and should be the job of a utility function/method; the interface will only return what it is given.

**Comment by Tobion** [comment]
> What I'm unsure of is whether you think this is acceptable, or if you suggest we change the spec to return / when no path is specified (per section 6.2.3). Can you please clarify?

I think both solutions are ok. It just has to explicitly documented IMO because it has big impact on routing for example. In symfony for example the routing path is always `/` at least. So if getPath would return an empty string under some circumstances the homepage would not match anymore.

**Comment by Tobion** [comment]
Given the other open issues and PRs about these topics, I close this.
