### ISSUE TITLE
[PSR-7] Why you use non standard prefixes "with/without" instead of "set/unset"?

### ISSUE THREAD

**Issue by LastDragon-ru** [php-fig/fig-standards#431]
Standard prefixes in PHP is "set/unset" but not "with/without". Why you don't use it?

```php
MessageInterface::withProtocolVersion()
MessageInterface::withHeader()
MessageInterface::withoutHeader()
etc
```

**Comment by sensorario** [comment]
I am not sure but, ... I think the reason is that MessageInterface is thinked as a Value Object. Value Object are immatable. So, ... how can you mutate (set) a value is a method must be side effect free? And each method must replace completely the previous.

**Comment by ashnazg** [comment]
That's covered in the metadoc...

**Comment by LastDragon-ru** [comment]
> Messages are values where the identity is the aggregate of all parts of the message; a change to any aspect of the message is essentially a new message
IMHO

1) in real life is not true - servers/proxies/etc can change the message (add/replace header)

2) normal (mutable) objects is more useful and requires less resources (no anonymous objects)

I think will be better use mutable objects with standard methods set/unset (and maybe ArrayAccess for headers). If API is really need immutable message it can use a `readonly` property  (for example) and exceptions (we can reset it after cloning and get a new mutable object).

**Comment by janwalther** [comment]
In PHP we have had a mutable value object: [DateTime](http://php.net/manual/de/class.datetime.php). Finding errors caused by the mutability is really a nightmare! The authors of the DateTime class admitted that it was a mistake to make the class objects mutable. Please do not repeat the same mistake: Value objects must not be mutable!

**Comment by weierophinney** [comment]
Please read the section entitled "Why value objects" in `proposed/http-message-meta.md`.

@pmjones , @dragoonis , or @philsturgeon -- please close.

**Comment by LastDragon-ru** [comment]
@weierophinney, I read it and I see:

> * most clients and server-side applications will need to be able to easily update message aspects
> * Most popular PHP frameworks have fully mutable HTTP messages today.

But this "standard" use immutable message...

+ method chaining is good in theory, but in practice we get unreadable code:
```
$myCustomObject = new Message();

if ($thisIsImportantSetting1 == 'value 1') {
    $myCustomObject = $myCustomObject->with('xxx');
}

if ($thisIsImportantSetting2 == 'value 2') {
    $myCustomObject = $myCustomObject->with('yyy');
}
```

@janwalther, I think it's different cases. IMHO, if API is really need immutable message will be better:

```
<?php
interface Message {
    public function isReadonly();
    
    // ...
}

class MessageImpl implements  Message {
    private $isReadonly = false;
    
    public function __construct($isReadonly = false) {
        $this->isReadonly = (bool) $isReadonly;
    }
    
    public function isReadonly() {
        return $this->isReadonly;
    }
    
    public function addHeader($name, $value) {
        if ($this->isReadonly()) {
            throw new Exception();
        }
        
        // ...
    }
}
?>
```

**Comment by janwalther** [comment]
<pre>$myCustomObject = new Message();
if ($thisIsImportantSetting1 == 'value 1') {
    $myCustomObject = $myCustomObject->with('xxx');
}
</pre>
What is unreadable here?
Imagine your Message class would be mutable and you use this object in two different code locations A and B. When A changes the object, an error could occur on B without actually having changed anything in B. Such side effects are really difficult to debug.

**Comment by LastDragon-ru** [comment]
> What is unreadable here?
`$myCustomObject = ` (IMHO of course)

> When A changes the object, an error could occur on B

Yes, this is maybe critical for `DateTime`, but if you add/delete headers or modifying message body is not critical and not an error (moreover it is a normal situation in real word).

**Comment by weierophinney** [comment]
@LastDragon-ru This subject has been debated extensively on the mailing list, and, frankly, you're not bringing anything new to the table. In point of fact, your example of making a read-only implementation is backwards; you should typically go from more strict to less strict (i.e., read-only to read-write), and one of the big arguments made for immutable contracts is that an implementation can choose to add mutability to an immutable version, but not vice versa.

This is also why the methods are named `with*()`. If we'd kept them as `set*()`, the implication is that we'd be changing the state of the instance, while `with()` implies I want a _new_ instance _with_ the given changes.

Regarding:

> if you add/delete headers or modifying message body is not critical and not an error (moreover it is a normal situation in real word)

frankly, I disagree. RFC-7230 states that a message is the sum of its parts. Changing any aspect of the message is essentially creating a new message. This is why we modeled the messages as value objects, to make that semantic clear.

Yes, you may build a request you're going to send iteratively, or a response you're going to return iteratively, but _each change is a new message_. By incorporating the `with*()` methods, we provide the interfaces with a simple mechanism for returning those new instances, and the only rule a developer needs to remember is to assign on change.

I appreciate your concerns, but also respectfully request that you read through the various mailing list threads, as everything you have cited so far has been argued previously. We have in fact placed PSR-7  in Review state at this time, as consensus is that the current design achieves the goals set for the specification.
