### ISSUE TITLE
[PSR-7] Why all modifying methods create a new instance of a object?

### ISSUE THREAD

**Issue by LastDragon-ru** [php-fig/fig-standards#432]
> Create a new instance with the specified HTTP protocol version.
> Create a new instance with the provided header, replacing any existing values of any headers with the same case-insensitive name.
> Create a new instance, with the specified message body.
> etc.

PHP have a `clone` operator and I think you must use it if you need a new object:

```рhp
// now
$message = $message->withHeader('foo1', 'bar1') // new anonymous object 1
    ->withHeader('foo2', 'bar2')  // new anonymous object 2
    ->withHeader('foo3', 'bar3'); // $message (new  anonymous object 3)

// must be
$newMessage = clone $message;

$newMessage
    ->setHeader('foo1', 'bar1')
    ->setHeader('foo2', 'bar2')
    ->setHeader('foo2', 'bar3');
```

**Comment by sensorario** [comment]
Value Object ...

**Comment by weierophinney** [comment]
This is covered in the meta document. Please see the section entitled "Why value objects?" in `proposed/http-message-meta.md`.

@pmjones , @dragoonis , or @philsturgeon -- please close.
