### ISSUE TITLE
Need definitive standards for folder name capitalization. 

### ISSUE THREAD

**Issue by MichaelBanks** [php-fig/fig-standards#434]
Do we name root folders (and sub-directories for that matter) as we do class names in StudlyCaps or camelCase or lowercase?

**Comment by samdark** [comment]
I don't think it should be regulated because in general according to autoloading PSRs folders must match namespace which is allowed to be both StudlyCaps and camelCase.

**Comment by philsturgeon** [comment]
You can name those folders anything you like! :+1:
