### ISSUE TITLE
Tests for implementations

### ISSUE THREAD

**Issue by janwalther** [php-fig/fig-standards#435]
The descriptions including examples of the PSR-standards (especially those defining interfaces) are really great but as tests say more than a thousand words would it be possible to offer PHPUnit tests? For example for PSR-7 the document includes the following [example](https://github.com/php-fig/fig-standards/blob/master/proposed/http-message.md#12-http-headers):
```php
$message = $message->withHeader('foo', 'bar');

echo $message->getHeader('foo');
// Outputs: bar

echo $message->getHeader('FOO');
// Outputs: bar
```

Of course we can read the whole document and look for certain more or less hidden specifications but an implementation can never be certain whether it is fully complying the standard. Wouldn't it be nice to offer a test suite as part of the standard specification? For the example above a test could look like:
```php
class MessageObligatoryTest extends PHPUnit_Framework_TestCase {
  public function testGetHeaderCaseInsesitive() {
    $message = new Message(); // not sure of this class in reality would be abstract, then this instantiation would not work
    $message = $message->withHeader('foo', 'bar');

    $this->assertEquals('bar', $message->getHeader('foo'));
    $this->assertEquals('bar', $message->getHeader('FOO'));
  }
}
```
And because some specifications are obligatory (MUST) and some are recommendations (SHOULD), I suggest multiple test suites (for each of these specification types).

**Comment by MacDada** [comment]
:+1: It would make checking correctness of implementations easier (than just reading the document over and over again to see if everything is covered).

**Comment by samdark** [comment]
:+1:

**Comment by michaelcullum** [comment]
The spec is finalised so cannot be changed but you are welcome to discuss changes to the meta document or a utils repo on the mailing list.
