### ISSUE TITLE
PSR-7 Misplaced Interfaces

### ISSUE THREAD

**Issue by drrcknlsn** [php-fig/fig-standards#437]
Please consider moving `StreamableInterface` and `UriInterface` into separate PSRs/namespaces.  [See here](https://www.reddit.com/r/PHP/comments/2wbhgr/psr7_http_message_interface_has_entered_the/copgdrl) for justification.  TL;DR is that future PSRs could need to make use of streams or URIs, and having to depend on an HTTP message package for those interfaces is not ideal.

**Comment by philsturgeon** [comment]
Please post this on the mailing list.

**Comment by Faryshta** [comment]
why not talk about it here?

**Comment by GrahamCampbell** [comment]
> why not talk about it here?

Because that's not how it works.

**Comment by Faryshta** [comment]
why?

**Comment by philsturgeon** [comment]
On github you only have the people who pay attention to GitHub. On the mailing list you have the attention of the entire mailing list, and they're the folks you need to talk to to affect change, even about topics that are already done to death.
