### ISSUE TITLE
Event based programming

### ISSUE THREAD

**Issue by Marlinc** [php-fig/fig-standards#44]
Why not create a standard for event based programming in PHP?

So if you have a application with loop you can use the standard that describes events.

So you have a event like this:

```php
<?php

abstract class Event
{

    public $nameLevel = 2;

    public function getName()
    {
        return end(explode('\\', get_class($this), $this->nameLevel + 1));
    }

}
```

And a event-handler like this:

```php
<?php

class EventHandler
{

    static protected $callbacks = array();
    
    protected $events           = array();
    
    public static function raise(Event $event)
    {
        foreach (self::$callbacks[$event->getName()] as $callback) {
            call_user_func($callback, $event);
        }
    }
    
    public static function addCallback(event, $callback)
    {
        self::$callbacks[$event->getName()][] = $callback;
    }

}
```

So you can add a callback to a event with:

```php
<?php

function onClick(Event $event)
{
    printf('Raised event %s', $event->getName) . PHP_EOL:
}

EventHandler::addCallback(new Clicked(), 'onClick');
```

And you're able to raise the event with:

```php
<?php

EventHandler::raise(new Clicked());
```

I'm sorry if this doesn't look the way you wan't it but this is just my idea. I'm open to suggestions and would like to get some feedback. And possibly event a standard for event based applications.

Also how do you think about event-based data like a 'nickname' for a user when he joins a IRC channel. Should this information be saved in a extended event class. In the raise method. Or something else?

**Comment by michaelcullum** [comment]
We discuss new proposals for PSRs on the mailing list first normally. If you'd like to continue with this, please suggest it on there where we can discuss it going to a potential entrance vote.

https://groups.google.com/forum/#!forum/php-fig
