### ISSUE TITLE
Russian translation mistake PSR-2

### ISSUE THREAD

**Issue by martinboy** [php-fig/fig-standards#457]
Mistake in point 2.3 in the following string:
<pre>НЕОБХОДИМО оставлять пробелы в конце непустых строк.</pre>
should be
<pre>НЕДОПУСТИМО оставлять пробелы в конце непустых строк.</pre>

**Comment by samdark** [comment]
@martinboy could you create a pull request?

**Comment by luchaninov** [comment]
It's already fixed in this commit
https://github.com/php-fig/fig-standards/commit/cd29bfaba5c57dfd04d90470bb489600eb975d10

Alex, you can close this issue.

**Comment by samdark** [comment]
Anyone with repo contributor access? Please close the issue.
