### ISSUE TITLE
[Propse to change] Closures MUST be declared with a space after the function keyword

### ISSUE THREAD

**Issue by kfuchs** [php-fig/fig-standards#463]
I propose changing how [Closures](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#6-closures) are declared. Instead of:

`Closures MUST be declared with a space after the function keyword` 

I feel it should be

`Closures MUST be declared with with an opening parenthesis followed directly after the function keyword. There MUST be NO spacing between the function keyword and the opening parenthesis`

Example: 

    $closureWithArgs = function($arg1, $arg2) {
        // body
    };

There is no reason why a space should exist in this type of function declaration but not in others. It's just simply consistent with every other function declaration. It also happens to be the more common declaration in javascript as well.

Thoughts?

**Comment by MacDada** [comment]
1. Replace spaces with underscores to see that it actually is consistent.

        function_name()_{
            // it's got a name
        };
        
        function_()_{
            // it doesn't, so name only is removed
        };

2. Not sure which way it is more popular in JS, but I've seen it both ways.

3. It's an accepted standard, isn't it a little too late to make objections?

**Comment by michaelcullum** [comment]
The spec is finalised but should you believe this is a typo/formatting issue or worthy of errata, please post it to the mailing list.
