### ISSUE TITLE
Translate PSR-4 to Indonesian

### ISSUE THREAD

**Issue by aprillins** [php-fig/fig-standards#476]
Hello,

Since the development of web thing in Indonesia has been expanding, I regard the PSR-4 documentation will be useful if it's available in Indonesian.

So, I have translated the [PSR-4 to Indonesian](https://github.com/aprillins/fig-standards) and I haven't make any pull requests yet. I'm waiting for permission from @philsturgeon and his suggestion about which files should be useful the most if it's translated.

Thanks,
Aprillins

**Comment by michaelcullum** [comment]
This should be closed now @samdark
