### ISSUE TITLE
What should ServerRequestInterface->hasHeader('host') return if the Host wasn't explicitly set?

### ISSUE THREAD

**Issue by mnpenner** [php-fig/fig-standards#478]
The `getHeaders`, `getHeader` and `getHeaderLines` methods all return a value for "Host" even if it wasn't explicitly set. Does this mean `hasHeader('host')` should always return `true`, or should it only return `true` if it was set with `withHeader`/`withAddedHeader`?

**Comment by weierophinney** [comment]
It should only return `true` if it was added via `withHeader()`/`withAddedHeader()` (i.e., if it was explicitly provided to the instance).

**Comment by mnpenner** [comment]
Okay. That's what I thought. Thanks for the clarification.
