### ISSUE TITLE
"Editor Plugins" wiki links are dead

### ISSUE THREAD

**Issue by GrahamCampbell** [php-fig/fig-standards#484]
Only 1 of the 3 actually is correct anymore.

**Comment by GrahamCampbell** [comment]
https://github.com/fabpot/PHP-CS-Fixer links to the wrong version of php-cs-fixer, and http://www.soulbroken.co.uk/code/sublimephpcs/ is an error 404.

**Comment by GrahamCampbell** [comment]
Also, surely it would be better to link people code sniffer github, rather than pear: http://pear.php.net/package/PHP_CodeSniffer. Who uses pear anymore?

**Comment by michaelcullum** [comment]
Where are these linked to I think was what @samdark meant.

**Comment by samdark** [comment]
I've finally figured out which article was meant and fixed it :)
