### ISSUE TITLE
UriInterface: Should we encode plus (+) to %2B?

### ISSUE THREAD

**Issue by mnpenner** [php-fig/fig-standards#505]
The spec says that we "MUST NOT double-encode any characters".

Does this mean we should interpret `+` as an already escaped SPACE or a literal `+` character that needs encoding?

RFC 3986 says that we should encode SPACE as `%20`, so running a query string or path through `withQuery` or `withPath` will not cause a double-encoding if `%20` is used, but if the query string is already escaped via some other means such as `http_build_query` which uses `+` by default then `withQuery` will cause a double-escaping because it abides a different standard (RFC 1738).

If, on the other hand, we leave `+` alone, then developers might erroneously think their `+` will be properly escaped to `%2B` because `UriInterface` uses RFC 3986.

I don't know what the best solution is. I stumbled across this problem when I ran a `+`-encoded query string through my Uri implementation and it mangled the URI because it uses a different standard.

**Comment by weierophinney** [comment]
The double-encoding referenced pertains to percent-encoding. RFC 3986 indicates a set of "reserved" characters, including `+`, which may be used as delimiters within components. It states:

> If data for a URI component would conflict with a reserved character's purpose as a delimiter, then the conflicting data must be percent-encoded before the URI is formed.

Essentially, it comes down to where you're using the `+` character. It looks like you're using it in `http_build_query`, to create a query string. In that context, `+` is valid and does not need to be percent encoded.

**Comment by mnpenner** [comment]
That's a bit vague. What does "valid" mean? It won't cause an error, sure, but it can ambiguously represent either a space or a literal plus character depending on which standard you follow. PHP will interpret it as a space when it parses it into `$_GET`.

To give you some examples, one person might write:

    $uri->withQuery(http_build_query(['q' => 'foo bar']))

Which he might then stuff into an `<a href="xxx">`, and then he would logically expect to get back `$_GET['q'] === 'foo bar'` on the server when that link is clicked. If we leave the `+` produced by `http_build_query` alone that's exactly what will happen.

On the other hand, someone else might write:

    $uri->withQuery('equation=3+4')

And expect our handy `Uri` class to do the right thing and give him back `$_GET['equation'] === '3+4'`, but instead he will get `'3 4'`. Shouldn't `&` and `=` be the *only* special characters in this context?

You wrote:

>  In that context, `+` is valid and does not *need* to be percent encoded.

Assuming it is encoded, should it be encoded as `%20` or `%2B`?

**Comment by weierophinney** [comment]
If it is intended as a space, and you know the target server will translate it as a space, leave it unencoded. If it is meant as a literal value, and not a delimiter, encode it. When in question, provide an encoded space instead of relying on http_build_query (which is easy to do by calling str_replace prior to calling http_build_query).

The fact that php will translate `+` to a space has nothing to do with RFC 3986, which is what we're targeting here in order to create uris that will work anywhere.

One additional note: you can actually change, via an INI seeing, php's behavior with regard to this to make it confirm to the rfc.

**Comment by mnpenner** [comment]
Okay. I'll leave it up to the caller to encode it then, and have my `UriInterface` implementation leave it as-is. I think this is the best solution anyway.
