### ISSUE TITLE
[PSR-7] ServerRequestInterface::getParsedBody() violates interoperability

### ISSUE THREAD

**Issue by m00t** [php-fig/fig-standards#507]
I think we should resume discussion about `getParsedBody()` method started by @geekwright here: https://groups.google.com/d/msg/php-fig/lzw4fbi_xXs/r0CEJ3V7zOkJ.
I agree with @geekwright that this method violates interoperability. 
Let's start discussion from another end, may be we can understand the issue that I think is here in a more clear and simple way. 
Let's say we create update user controller which receives JSON and **knows nothing** [*this is very important for interoperability*] about what PSR-7 implementation it will be used with. Which way this can be done? The simplest and the most straightforward way to do this is that:
```php
function update_user_action(ServerRequestInterface $request) {
    $userData = json_decode((string) $request->getBody());
    // update user
}
```
If I understand correctly, the main goal of changing method `getBodyParams()` to `getParsedBody()` in theory was that we can write something like this:
```php
function update_user_action(ServerRequestInterface $request) {
    $userData = $request->getParsedBody();
    // update user
}
```
But this code is not compatible with current state of PSR-7. Because PSR-7 does not guarantee that `ServerRequestInterface` will return parsed array (or stdObject) from `getParsedBody()` when it receives request with content-type `application/json`. In order to make this code correct, we should add this statement to PSR-7: 
```
Method getParsedBody() MUST return an array when request has content-type application/json
```
Hooray! We just made `getParsedBody()` correctly parse one body format out of infinite amount of this formats!

To address this issue, @geekwright proposed introducing body parsers. I disagree with him, but my disagreement is rather subjective: because in my opinion this will overcomplicate standard. There also some objective arguments against this proposal: @weierophinney noted that it can be very hard to serialize/deserialize request with arbitrary body parsers in it which can hold connections to database and other hard to serialize things.

I propose another way of addressing this issue. I think we should remove arbitrary body parsing out of PSR-7 completely.

What if we do not want to write `json_decode()` in every controller? Then you should not use `ServerRequestInterface` in it, that is all! You can write something like this:
```php
function update_user_action(MySuperJsonRequest $request) {
    $userData = $request->getParsedJson();
    // update user
}
```
And then you should wrap incoming `ServerRequestInterface` with your `MySuperJsonRequest` **in your front-controller**. This is exactly the way @evert proposed here: https://groups.google.com/d/msg/php-fig/lzw4fbi_xXs/ZHk9j5EG9IIJ. And then there was a conversation between him and @simensen about this topic where I can not understand arguments from @simensen and this conversation was not ended properly:

>>> Worried that you can't use other PSR-7 requests in your application? 
This was the case before as well. You needed to already 'extend' the 
PSR-7 message with your own arbitrary data, likely resuling in a call to 
withAttribute(), withParsedBody(). This time you spawn an instance of 
MyRequest that could easily decorate a real PSR-7 Request. 

>> Except that we've shown that in practice this does not actually work, right?

> ServerRequest extends Request, and also provides additional methods. Why 
wouldn't this work? 
Even if you don't like the idea of extending/decorating, it can also 
still also be solved using composition.

The last question from @evert was just ignored by @simensen without any arguments.

A word about attributes. I think, @evert ad @simensen disagree with each other only because they are missing the point of each other. For example we have this controller:
```php
function update_user_action(ServerRequestInterface $request) {
    $userData = $request->getAttribute('parsed-json');
    // update user
}
```
Seems like this badly violates PSR-7 standard and interoperability. But it is not. At least not so badly. Actually the real consumer of PSR-7 is not `update_user_action()`. **The real consumer of PSR-7 here is a front-controller** which sets attribute:
```php
function front_controller(ServerRequestInterface $request) {
   if ($request->getUri()->getPath() === '/update-user.json') {
        $requestWithJson = $request->withAttribute('parsed-json', json_decode((string) $request->getBody()));
        update_user_action($requestWithJson);
   }
}
```
Function `update_user_action()` will not be used without `front_controller()`, and `front_controller()` does not violate PSR-7 and interoperability.

But I still prefer that these functions should be rewritten in proposed by @evert way:

```php
function front_controller(ServerRequestInterface $request) {
   if ($request->getUri()->getPath() === '/update-user.json') {
        $jsonRequest = new MySuperJsonRequest($request, json_decode((string) $request->getBody()));
        update_user_action($jsonRequest);
   }
}
function update_user_action(MySuperJsonRequest $request) {
    $userData = $request->getParsedJson();
    // update user
}
```

**Comment by m00t** [comment]
Also, this front-controller and controller can be rewritten this way:
```php
function front_controller(ServerRequestInterface $request) {
   if ($request->getUri()->getPath() === '/update-user.json') {
        $requestWithJson = $request->withParsedBody(json_decode((string) $request->getBody()));
        update_user_action($requestWithJson);
   }
}
function update_user_action(ServerRequestInterface $request) {
    $userData = $request->getParsedBody();
    // update user
}
```
Which technically the same as `getAttribute('parsed-json')` and does not violate interoperability much too, if (the same for attributes) we ensure that every interface user and implementation understands this statement:

**Interface implementation can not parse request body itself except for $_POST contents. It can only return something that its client set previously by calling withParsedBody().**

**Comment by weierophinney** [comment]
@m00t — You're missing an important point: we're not specifying that `getParsedBody()` MUST be populated (with the exception that if we have a POST request in `application/x-www-form-urlencoded` or `multipart/form-data`).

I completely disagree that the front controller should ensure the value is populated. In many cases, you may not want to parse the body unless certain conditions are met. As an example, consider an API: you may want to first ensure you have a valid path, that the HTTP method is valid for that path, that the user is authenticated, and that the identified user is authorized to perform the requested action. If any of these conditions are not met, there is *no* reason to parse the body; we can simply return immediately.

The above could be done as discrete middleware as well:

- routing
- HTTP method validation
- authentication
- authorization
- **body parsing**
- content validation
- execution of selected controller

Each is a discrete task, and each may create a new request instance with updated values and pass it to the next.

This takes me to the next point: the selected controller may not need to care *how* the data was parsed, but that it has acceptable data. As an example, perhaps we want to allow our API to respond to either XML or JSON payloads. In each case, parsing should return the same structure. The controller only cares that it has the data, not how it came in. The same API could even respond to form-encoded data if desired.

By allowing middleware to intercept and parse, and then push to a well-known location, our controller only needs to know where to get the data. And **that** is the whole reason we chose to include `getParsedBody()`, along with a mutator for injecting and returning a new instance with the parsed parameters. It exists for exactly the reason you state: to promote interoperability and ease discovery for consumers.

**Comment by m00t** [comment]
@weierophinney I agree with you completely here. Use front-controller to call `withParsedBody()` and use middleware here are conceptually identical. I use `front_controller()` just to simplify things.

Look, you have your application. May be it based on some framework, or not. It may use stack-php-like middleware structure, or use your conduit, it does not matter. 

What matters here: you controller MAY assume some of your middlewares will call `withParsedBody()`.

But your whole application (`front_controller()` in my example) also receives `ServerRequestInterface`: from your test suite or from `Phly\Http\Server::listen()` call, right? And what matters here: you whole application MUST NOT assume that someone (`Server` or tests) call `withParsedBody()` before it sends `ServerRequestInterface` to your application. 

This is in my opinion the source of disagreement between all of us. 

One side said (@geekwright, @evert and me) that `withParsedBody()` violates interoperability. And we mean "your whole application MUST NOT assume that someone call `withParsedBody()` before it sends `ServerRequestInterface` to it".

The other side (you, @simensen)  said it is ok, and subjectively a bit better than using attributes. And you mean "your controller MAY assume some of your middlewares will call `withParsedBody()`".

**Comment by weierophinney** [comment]
@m00t You're summing up the argument well. I, and others, feel that there are performance benefits to not requiring that the body params be populated at instantiation. This does *not* prevent an implementation from doing so, but by not requiring that they be present at instantiation, we can also allow for this performance trick.

Using attributes ties applications to specific implementations and promotes a convention-based approach. Many (@Crell in particular) feel that this makes the situation more difficult for consumers, as they need to know what potential conventions are in use, and thus makes code less portable (do I look in the "body" attribute? or the "parsed" attribute? or do I need to know what format it came in as, and look under an attribute with that name?)

If the parsed body is _always_ injected into a single known location, consumption is predictable. The result is a stronger interface.

**Comment by m00t** [comment]
@weierophinney I am glad we have overcome our disagreement here. I am closing this issue.
