### ISSUE TITLE
"a HTTP xxx" => "an HTTP xxx"

### ISSUE THREAD

**Issue by webmozart** [php-fig/fig-standards#514]
I was a bit confused that the PSR uses "a" in stead of "an" before "HTTP", such as "a HTTP message". AFAIK the PSR uses British spelling, for which I found the following [source at the BBC](http://www.bbc.com/news/magazine-11642588):

> British English dictionaries give aytch as the standard pronunciation for the letter H. However, the pronunciation haytch is also attested as a legitimate variant. We also do not ask broadcasters who naturally say haytch to change their pronunciation but if a broadcaster contacted to ask us, we would tell them that aytch is regarded as the standard pronunciation in British English

Hence I would change "a HTTP message" and similar occurrences to "an HTTP message".

See [a related conversation on Twitter](https://twitter.com/webmozart/status/587543333037330432) if you're interested.

**Comment by weierophinney** [comment]
There were exactly **two** occurrences of this in the entire spec. ;-)

**Comment by webmozart** [comment]
@weierophinney Ha, then they only stuck out :) I thought they were by intention. Thanks for fixing!
