### ISSUE TITLE
Sending requests with query/request params, cookies and files

### ISSUE THREAD

**Issue by webmozart** [php-fig/fig-standards#515]
Consider you are building some sort of library that takes a PSR-7 request, adds a query parameter and a file to the request and finally sends the request with an HTTP client such as Guzzle:

```php
$queryParams = array_replace($request->getQueryParams(), array('is_upload' => '1'));

$request = $request->withQueryParams($queryParams)
    ->withUploadedFiles(array('file' => new File('/path/to/file'));

$client->send($request);
```

The above cannot be implemented at the moment, since `withQueryParams()` et al. don't exist in `RequestInterface`, only in `ServerRequestInterface`, which states:

> Representation of an incoming, server-side HTTP request.

Hence `ServerRequestInterface` is not appropriate for modeling client side requests.

I think that we should move the following methods to `RequestInterface` in order to facilitate building of requests on the client side:

* `*CookieParams()`
* `*QueryParams()`
* `*ParsedBody()`
* `*UploadedFiles()`

Doing this exposes a further weakness: `withParsedBody()` cannot be used on the client, as the PSR currently does not expect implementations to update the stream returned by `getBody()` when `withParsedBody()` is called. However, that's probably a separate issue.

**Comment by m00t** [comment]
Alternatives:

1. Remove client side requests from the scope of PSR-7
2. Make separate `ClientRequestInterface` which can be used when dealing with libraries like Guzzle.

**Comment by Tobion** [comment]
Why not simply change the doc for ServerRequestInterface. From my point of view ServerRequestInterface is just an enhanced RequestInterface that exposes common methods for working with a request, e.g. parsed query, which are not defined in the HTTP specification.

**Comment by m00t** [comment]
Al I mentioned in #516, I think the problem is that methods

* withCookieParams()
* withQueryParams()
* withUploadedFiles()

are client request methods. And these

* withParsedBody()
* withAttribute()

are server request methods in my opinion. 

So the best option, for me, would be to introduce `ClientRequestInterface` where first 3 mentioned methods will be moved from `ServerRequestInterface`

**Comment by webmozart** [comment]
@m00t Not necessarily. Server middleware may take an incoming request, modify it and pass it on.

**Comment by m00t** [comment]
@webmozart what is the purpose of modifying incoming request cookies or files?

**Comment by webmozart** [comment]
@m00t Backwards compatibility layers for example which adapt requests for old applications.

**Comment by weierophinney** [comment]
> Remove client side requests from the scope of PSR-7

@m00t : you're missing an important detail. PSR-7 was created to model HTTP messages specifically, and the original editors are _authors of client libraries_. Addition of server-side specific details were only added after I got involved last September.

Removing client-side aspects would essentially make this a completely different proposal. The goals are to model HTTP messages; ServerRequestInterface (and its related interfaces) exist to aid with server-side applications, where we likely don't want to have to parse the query string manually, or parse the URI manually, or parse the body manually (though this will likely need to be done at *some* point), but instead just consume that data. Having the ability to inject parsed variants (either from superglobals or from processes that parse these components) makes consumer use cases easier.

That said, having a general request and response interface makes creating _clients_ very easy. We want to be able to address *both* sides of the equation.

**Comment by weierophinney** [comment]
> what is the purpose of modifying incoming request cookies or files?

@m00t : Can you *please* go and read the various PSR-7 threads in the mailing list? This stuff has been hashed out *numerous* times. In short: some frameworks perform cookie encryption, decrypt uploaded files on the fly, etc.

**Comment by m00t** [comment]
@weierophinney Understood, thanks. Sorry for messing things up.

**Comment by weierophinney** [comment]
@webmozart This is a massive departure from what we've been proposing. As noted on the mailing list, I think we need to stop making massive changes, and instead focus on whether what we have *works* for a large number of use cases. @mtdowling has shown already that PSR-7 works quite well for client-side applications *without* any of the changes you're proposing here. I and others have shown that it works well for server-side applications. Yes, we can entertain such changes, but we should also be keeping an eye on "good enough."

**Comment by mtdowling** [comment]
Yeah, -1 to this idea. Having written a client library and an AWS SDK using both techniques, I prefer the RequestInterface and ResponseInterface in PSR-7. I'm not using ServerRequestInterface in Guzzle because it's not necessary for a client (I'm not sure it's necessary at all really, but that's a different story).

We could try to get things like query string abstractions right, but we wouldn't. It's too complex and there's too many different ways to go from an array to a string and vice versa.

I added helper functions to Guzzle's PSR-7 package to parse and serialize query strings. These things don't have to be in the PSR and can be handled in libraries as external functions (note: not subclasses) where they are free to be wrong and easily changed for a better function if ever needed to accommodate unforeseen edge cases.

**Comment by webmozart** [comment]
@mtdowling Could you give an example of how my above code snippet would look like with Guzzle's PSR-7 package?

**Comment by mtdowling** [comment]
Sure. Here's an example of [query string handling](https://github.com/guzzle/psr7/blob/master/src/Uri.php#L235) from the [tests](https://github.com/guzzle/psr7/blob/master/tests/UriTest.php#L159):

```php
$uri = new Uri('http://foo.com/bar');
$uri = Uri::withQueryValue($uri, 'a', 'b');
$uri = Uri::withQueryValue($uri, 'c', 'd');
$uri = Uri::withQueryValue($uri, 'e', null);
$this->assertEquals('a=b&c=d&e', $uri->getQuery());

$uri = Uri::withoutQueryValue($uri, 'c');
$uri = Uri::withoutQueryValue($uri, 'e');
$this->assertEquals('a=b', $uri->getQuery());
$uri = Uri::withoutQueryValue($uri, 'a');
$uri = Uri::withoutQueryValue($uri, 'a');
$this->assertEquals('', $uri->getQuery());
```

Application specific middlewares that might be modifying the query string or request body parameters multiple times could potentially pass around an application specific context to prevent the need to parse the query string between each middleware.

In practice in the SDK, we typically build up the query string and serialize it before associating it with a request: https://github.com/aws/aws-sdk-php/blob/abstract-http/src/Api/Serializer/QuerySerializer.php

In some cases, we're given a request that may have application/x-www-form-urlencoded parameters in the body. In this case, we parse the body to modify the parameters: https://github.com/aws/aws-sdk-php/blob/abstract-http/src/Signature/SignatureV2.php#L18

For super performance critical things with lots of mutations, we build up a request using a mutable representation and then serialize it as a PSR-7 request: https://github.com/aws/aws-sdk-php/blob/abstract-http/src/Signature/SignatureV4.php#L77

One thing that we don't want to do is couple our HTTP message abstractions with PHP specific assumptions. For example, some APIs allow query string values to be represented using the same key multiple times (i.e., "foo=1&foo=2"). How would we differentiate repeated key serialization from PHP style serialization (i.e., "foo[0]=1&foo[1]=2") or languages that represent this as "foo[]=1&foo[]=2" without overly-complicating the spec? I also think abstractions on the message for specific stream serializations is a code smell as well. Why have "form" related methods when we don't have JSON, XML, Yaml, ... etc... methods? (to be clear, I am not suggesting we add these methods)

**Comment by michaelcullum** [comment]
PSR-7 is now final and cannot be changed. If you want to discuss anything further you're of course welcome to do so on the mailing list.
