### ISSUE TITLE
Response::withCookie

### ISSUE THREAD

**Issue by mnpenner** [php-fig/fig-standards#527]
`ServerRequestInterface` has a `getCookieParams` method, but there's no corresponding `Response::withCookie[Param]`. Shouldn't we add one?

The `ResponseInterface` method already deals with headers. I don't think the [setcookie](http://ca2.php.net/manual/en/function.setcookie.php) method should be used to set headers independently; this prevents middlewares from accessing/removing/manipulating/encrypting the cookies.

**Comment by weierophinney** [comment]
@mnpenner — The only reason we have the `*CookieParams()` methods in `ServerRequestInterface` is to have coverage of all the various PHP superglobals. For purposes of responses, cookies are just headers, and can be dealt with as such; a utility library can be used to aggregate cookies and their metadata (path, secure, ttl, etc.), and then inject appropriate headers into the response when desired. (@simensen is actually working on such a library now: https://github.com/dflydev/dflydev-fig-cookies)

**Comment by mnpenner** [comment]
I suppose you *could* do `$response->withHeader('Cookie', HttpUtil::cookieHeader(...))`. Fair enough.
