### ISSUE TITLE
Should StreamInterface::getContents advance the cursor?

### ISSUE THREAD

**Issue by mnpenner** [php-fig/fig-standards#528]
The doc-comment doesn't say whether or not `StreamInterface::getContents` should advance the cursor to the end of the stream or not.

**Comment by mtdowling** [comment]
It reads the remainder of the stream, so it advances the cursor.

**Comment by michaelcullum** [comment]
PSR-7 is final and we are currently in the process of deprecating the issues on this repository. Feel free to raise your thoughts on the Mailing List.
