### ISSUE TITLE
A question on multiline chained method calls and more...

### ISSUE THREAD

**Issue by pine3ree** [php-fig/fig-standards#542]
I like to use the following formats:
```php
$users = $userMapper
    ->sort($sorter)
    ->paginate($paginator)
    ->find()
;
//...
$user = $id > 0
    ? $userMapper->findById($id) //imagine this longer
    : null
;
```

having the ";" on the next line makes me think about control blocks opening and closing structure. Basically the semicolon on the first column of next line makes me think of it as a closing a block of related operation, wether multiple method calls or ternary expression.
```
if (true) {
    //doSomheting();
}
```

Is this (semicolon on next line) acceptable by PSR-2? I cannot find any reference about it

kind regards

**Comment by theofidry** [comment]
I'm also curious of the answer.

**Comment by frankbardon** [comment]
I can't seem to find anything in the spec, but a quick regex through the Symfony codebase shows it only happening in tests and documentation. I, too, use that syntax as I find it much easier to read and maintain. Perhaps it was intentionally left to the discretion of the developer? I don't see anything strictly forbidding it.

**Comment by theofidry** [comment]
StyleCI forbids it though.

**Comment by frankbardon** [comment]
I've never used it, perhaps the issue should be raised with them. Unless I'm missing something, there's no mention of the ternary operator anywhere in PSR-1 or PSR-2. I assume that the multi-line bit in PSR-2 applies to fluent setters as well, and that's just a four space indent...

There is a bit about allowing blank lines for readability, but a line containing `;` is obviously not blank. I think, at the moment, that would just leave the formatting up to the developer unless the code violates another part of either specification. 

@theofidry: Perhaps someone should submit this question to StyleCI. Perhaps they'll respond with their decision, relax their rules, or provide configuration options?

**Comment by michaelcullum** [comment]
This is not covered in PSR-2 which is final. If you think this deserves clarification in PSR-12 feel free to suggest it on the mailing list.
