### ISSUE TITLE
PSR-2 Line limits and long strings

### ISSUE THREAD

**Issue by Swader** [php-fig/fig-standards#545]
I suggest the line limit section of PSR-2 be updated with best practices regarding long strings.

For example, if I have a long exception message to output, it'll obviously span more than 120 characters. Splitting it up and concatenating line by line introduces some unreadable overhead and difficulty in editing it later on, using HEREDOC makes the code uglier due to not being indent-friendly, and just newlining introduces line breaks. None of the approaches look optimal, so I'm just curious about the general consensus on handling this.

What does the majority do? Any advice?

I know this seems trivial, but my OCD won't let me let it go.

**Comment by GrahamCampbell** [comment]
PSR-2 can't change. It's already fixed. It officially has NO line length limit.

**Comment by Swader** [comment]
I'm not asking for a change to the specification, merely for people's advice on handling these cases when one is intent on avoiding the 120-char warnings.

**Comment by GrahamCampbell** [comment]
> 120-char warnings.

There is no hard line limit. If you're referring to phpcs, they're not official, and any warnings they may give you might not actually reflect PSR-2.

**Comment by Swader** [comment]
I beg to differ.

> The soft limit on line length MUST be 120 characters; **_automated style checkers MUST warn_** but MUST NOT error at the soft limit.

**Comment by GrahamCampbell** [comment]
Hmmmm, I see. This does seem to be a floor in PSR-2, though we can;t really do anything about it. Chaning the context in which style checkers "MUST" warn is a breaking change to the spec, so isn't allowed.

**Comment by GrahamCampbell** [comment]
As far as I'm aware...

**Comment by Swader** [comment]
Yeah, like I said, I'm not asking for changes to the spec, it's fine as is and I like that style checkers must warn at 120+. I'm just looking for advice from people on dealing with this "problem", wondering how others do it when they encounter long string situations and still want to keep lines under 120.

**Comment by shadowhand** [comment]
I would argue that exceptions longer than 120 characters aren't going to be read by developers. One thing I do for longer exceptions is this:

```php
throw new InvalidArgumentException(sprintf(
    'Here is my long message about %s but making it a separate line with sprintf gives me more room',
    get_class($this)
));
```

It also works better when you start to break lines up:

```php
throw new InvalidArgumentException(sprintf(
    'Here is my long message about %s but making it a ' .
    'separate line with sprintf gives me more room and ' .
    'breaking it into multiple lines looks okay too.',
    get_class($this)
));
```

**Comment by morrisonlevi** [comment]
This snippet from the Linux kernel coding style is relevant:

> However, never break user-visible strings such as printk messages, because that breaks the ability to grep for them.

**Comment by GrahamCampbell** [comment]
@morrisonlevi I agree there.

**Comment by Swader** [comment]
> exceptions longer than 120 characters aren't going to be read by developers

I disagree, but can relate.

Breaking and concatenating like you did is OK, but it doesn't play well with refactoring later on, if you need to add more information into the message. It becomes an incredibly tedious process. Plus, there's @morrisonlevi's point on grepping. I'm somewhat inclined to use an external file sometimes, like mentioned in [the reddit thread](http://www.reddit.com/r/PHP/comments/34pqsz/how_do_you_handle_long_strings_in_respect_to_the/), but then the code loses read flow if you have to jump to another file to find out which message gets printed out by an exception.

I assume HEREDOCing also isn't grep friendly? In that case, seems like striving for short messages by any means or using external files is the way to go.

But then there's the case of, for example, long links. If I have a long link hardcoded (like in a test or something), that's both (mostly) unbreakable and not HEREDOC-able, and it's silly to have it in an external file. In cases like those, the only acceptable approach seems to be leaving the line long, which is really a thorn in my eye, especially when using splitscreen of 2-3 files. But yeah, OCD, I should just try and learn to shrug at the warnings and ignore them.

**Comment by michaelcullum** [comment]
The spec is finalised but should you believe this is a typo/formatting issue or worthy of errata, please post it to the mailing list.
