### ISSUE TITLE
Further cs recommendations: indentation for ->

### ISSUE THREAD

**Issue by tonglil** [php-fig/fig-standards#551]
I hope to propose a rule for the [next round of PSR that addresses cs](https://github.com/php-fig/fig-standards/wiki/Further-Style-Guide-Considerations).

A rule for indentation when using accessors `->` in fluent interfaces?

Examples (what I have seen around):

# 1) 4 spaces / 1 tab
```
$results = DB::table('name')
    ->where('column', true)
    ->select('*')
    ->get();
```

# 2) no indentation
```
$results = DB::table('name')
->where('column', true)
->select('*')
->get();
```

# 3) match the end of the "space"
```
$results = DB::table('name')
           ->where('column', true)
           ->select('*')
           ->get();
```
# 4) match the end of `::`
```
$results = DB::table('name')
               ->where('column', true)
               ->select('*')
               ->get();
```

# 5) no new lines
```
$results = DB::table('name')->where('column', true)->select('*')->get();
```

**Comment by dereuromark** [comment]
Inline alignment is bad as it creates a lot of unnecessary noise in diffs.
As such only option 1) is suitable, with 5) allowed if it is really short and a 1-liner.

**Comment by GrahamCampbell** [comment]
1 makes sense to me too.

**Comment by BernardoSilva** [comment]
1 looks the best one.

**Comment by shefik** [comment]
I agree with Mark S.:

> As such only option 1) is suitable, with 5) allowed if it is really short and a 1-liner.


-------------------------------------------------

Shefik
All Knight Access
+1 914-965-1216
+1 914-548-5033 mobile
shefik@allknightaccess.com
http://www.allknightaccess.com/

Portfolio: http://www.shefik.info/
LinkedIn: http://www.linkedin.com/in/shefik
Twitter: @shefik_info
GitHub: https://github.com/shefik
Open Source Report Card: http://osrc.dfm.io/shefik

The information contained in this message and any attachment may be proprietary, confidential, and privileged or subject to the work product doctrine and thus protected from disclosure. If the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify me immediately by replying to this message, and deleting it and all copies and backups thereof.

**Comment by digilist** [comment]
I'd like a rule for those kind of code. In my I think opinion 1 is the best.

I have another example to consider, when not using a static method call at first.

```php
$results = $db->getTable('name')
    ->where('column', true)
    ->select('*')
    ->get();
```

vs. 

```php
$results = $db
    ->getTable('name')
    ->where('column', true)
    ->select('*')
    ->get();
```

Should the first method call be on the same line as the variable (which is similar to your static example) or in the following line? I would prefer the second version, but that would require two separate rules (for static and non-static)

**Comment by shefik** [comment]
I would prefer this:

> $results = $db->getTable('name')
>     ->where('column', true)
>     ->select('*')
>     ->get();

-------------------------------------------------

Shefik
All Knight Access
+1 914-965-1216
+1 914-548-5033 mobile
shefik@allknightaccess.com
http://www.allknightaccess.com/

Portfolio: http://www.shefik.info/
LinkedIn: http://www.linkedin.com/in/shefik
Twitter: @shefik_info
GitHub: https://github.com/shefik
Open Source Report Card: http://osrc.dfm.io/shefik

The information contained in this message and any attachment may be proprietary, confidential, and privileged or subject to the work product doctrine and thus protected from disclosure. If the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify me immediately by replying to this message, and deleting it and all copies and backups thereof.

**Comment by bburnichon** [comment]
I would prefer option 1 with the same addon @digilist talked about for instance calls.

There are also some issues with fluent writing like in symfony extension configuration with things like:
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/DependencyInjection/Configuration.php#L40

```php
        $rootNode
            ->children()
                ->scalarNode('db_driver')
                    ->validate()
                        ->ifNotInArray($supportedDrivers)
                        ->thenInvalid('The driver %s is not supported. Please choose one of '.json_encode($supportedDrivers))
                    ->end()
                    ->cannotBeOverwritten()
                    ->isRequired()
                    ->cannotBeEmpty()
                ->end()
                ->scalarNode('user_class')->isRequired()->cannotBeEmpty()->end()
                ->scalarNode('firewall_name')->isRequired()->cannotBeEmpty()->end()
                ->scalarNode('model_manager_name')->defaultNull()->end()
                ->booleanNode('use_listener')->defaultTrue()->end()
                ->booleanNode('use_flash_notifications')->defaultTrue()->end()
                ->booleanNode('use_username_form_type')->defaultTrue()->end()
                ->arrayNode('from_email')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('address')->defaultValue('webmaster@example.com')->cannotBeEmpty()->end()
                        ->scalarNode('sender_name')->defaultValue('webmaster')->cannotBeEmpty()->end()
                    ->end()
                ->end()
            ->end()
```

So enforce 4 spaces will break the current convention where indentation offset can change according to the fluent interface design.

I would like convention to include this kind of indentation.

**Comment by tonglil** [comment]
@digilist I prefer the 1st way, and my suggestions are that we treat `::` the same as `->` as they are both accessors into the object.  The reasoning for one accessor per line is inspired by Java's "object calisthenics".

**Comment by tonglil** [comment]
@bburnichon mm I agree, that is a tricky one as the rules for indentation are not based on any part of the PHP language, but rather use defined to each "node".  Then again, that's a configuration file (that could be written in yml or as PHP arrays in other scenarios).

**Comment by digilist** [comment]
With your example, the first call is mandatory to call the further methods. However, if the method calls are interchangable (for example if you call setters on an entity class with fluent interface), it would be very annoying to exchange the first line. Example:

```php 
$user
   ->setName('Foo')
   ->setEmail('foo@bar.de')
;
```

(Btw another question regarding this topic: where to put the semicolon in the end? Right after the last statement or in the line below?)

**Comment by GrahamCampbell** [comment]
> (Btw another question regarding this topic: where to put the semicolon in the end? Right after the last statement or in the line below?)

:+1: for right after the last statament.

**Comment by tonglil** [comment]
@digilist I don't think so, it could be:
```php
$results = DB::where('column', true)
    ->select('*')
    ->table('name')
    ->get();
```
And using your example:
```php
$user->setName('Foo')
   ->setEmail('foo@bar.de');
```
Or
```php
$user->setEmail('foo@bar.de')
   ->setName('Foo');
```

But these are just recommendations and different versions.

The PSR is voted on so I suggest we provide as many variations and they can vote on them for the next round :).

**Comment by tonglil** [comment]
Keep in mind, the PSR isn't to make diffing easier (git can already diff between character changes in a line) but to recommend styling standards for consistency and in extension provide a reference for (especially new) PHP developers.

**Comment by digilist** [comment]
Yeah, right, but I am not thinking about diffing. I am thinking about moving lines up and down. I often do this in my daily work and I bet there are many other developers who work like this. This woul be something more difficult when the first statement is bound to the variable.

And you are right, we are only suggesting things, but I think that our discussions are also helpful to find a solution. :smiley:

**Comment by glen-84** [comment]
What about:

# 6) match the operator on the first line
```
$results = DB::table('name')
             ->where('column', true)
             ->select('*')
             ->get();
```

Non-static:
```
$results = $db->table('name')
              ->where('column', true)
              ->select('*')
              ->get();
```

Or (if line 1 is too long):

```
$results =
    $db->table('name')
       ->where('column', true)
       ->select('*')
       ->get();
```

**Comment by GrahamCampbell** [comment]
> match the operator on the first line

I really don't like that.

**Comment by glen-84** [comment]
It's the neatest and easiest to read, IMHO, since the method names are perfectly aligned.

**Comment by mwhitneysdsu** [comment]
I use 6 in most cases (though 1 is acceptable), with 5 if the line is less than ~80 characters and doesn't give me a headache. The static example for 6 bothers me, but my issue there has more to do with PHP than coding style, and I don't have a better recommendation there.

I understand the purpose of the differing indentation in fluent interfaces, and maybe there could be a reasonable variance in the specification for that, but I don't really know how I'd feel about coming across that in a method/function rather than a configuration file.

**Comment by GrahamCampbell** [comment]
Number 6 doesn't work if you say that all function calls MUST be on their own line.

**Comment by GrahamCampbell** [comment]
Which I think is a very good idea in terms of readable diffs.

**Comment by glen-84** [comment]
@GrahamCampbell I'm not sure what you mean – can you give an example?

**Comment by GrahamCampbell** [comment]
How can you align to the first one if it's not on the first line, is what i'm getting at.

**Comment by mwhitneysdsu** [comment]
You would align to the end of the variable, but that's something I wouldn't do myself.

```php
$results = $db
              ->table('name')
              ->where('column', true)
              ->select('*')
              ->get();
```

I don't find the difference in the readability of diffs to be significant, especially given the likelihood of the first line actually changing.

**Comment by glen-84** [comment]
It's probably best not to include this in the standard.

@bburnichon shows an example where a fixed indentation style is not ideal.

The furthest I would go is something like "the indentation of subsequent lines should either be divisible by 4 or aligned with the invocation on the previous line" (which covers options 1 & 6).

No. 5 should always be allowed when there is sufficient space.

**Comment by dereuromark** [comment]
Just use 1 and be done with it :) Easy, good to read/understand for humans, perfect for minimal diffs.

**Comment by mwhitneysdsu** [comment]
I'm fine with number 1, but you should look into some better diff software (or configuration of your existing software) if any of these recommendations has a significant impact on your diffs.

**Comment by michaelcullum** [comment]
FYI: None of this will apply to PSR-12 that I can see as we are looking to focus only on functionality introduced since PHP 5.4 and not break BC.

**Comment by michaelcullum** [comment]
Should you wish to discuss this further, please raise it on the mailing list.
