### ISSUE TITLE
PSR-2 Coding style array() vs []

### ISSUE THREAD

**Issue by stefanchiriac** [php-fig/fig-standards#574]
Hello,

There are a lot of posts regarding arrays declaration standards and everyone goes with whatever they want, but what should be the standard for PHP 5.4+ from FIG point of view?

Thanks

**Comment by samdark** [comment]
`[]`.

**Comment by stefanchiriac** [comment]
ok, thank you. I think it should be written in clear to avoid future confusions. Arrays are defined as [] in FIG coding style document, but seems to still be some question marks in php community if that's a standard or not.
