### ISSUE TITLE
PSR-4 echo error messages?

### ISSUE THREAD

**Issue by fulldecent** [php-fig/fig-standards#575]
PSR-4 states:

> Autoloader implementations MUST NOT throw exceptions, MUST NOT raise errors of any level, and SHOULD NOT return a value.

To clarify, is this referring only to `trigger_error()`?

For example, https://github.com/AuthorizeNet/sdk-php/blob/master/autoload.php this autoloaded produces the side effect

         echo 'Class not loaded: ' . $className;

when a class is not loaded by that specific autoloader. Is such a non-compliant "error" as specified by this rule?

**Comment by simensen** [comment]
I would say this is not compliant though I'm not sure that the text would agree. PSR-4 makes no claims (that I can find) about output though one would think that it would be common sense not to output anything like this in a classloader. /cc @pmjones

**Comment by fulldecent** [comment]
This is good enough for me to submit a PR to them to "fix" this. I'm not sure if the standard should also include such common sense.
