### ISSUE TITLE
[RFC] [PSR-2] Short type syntax

### ISSUE THREAD

**Issue by phansys** [php-fig/fig-standards#580]
Standardize the type keywords which have different versions, enforcing to use the shortest syntax:

Example:
```php
/* @var bool $someBoolExpr */
(bool) $someBoolExpr; // instead of (boolean)

/* @var int $someIntExpr */
(int) $someIntExpr; // instead of (integer)
```

**Comment by GrahamCampbell** [comment]
PSR-2 can't accept new rules.

**Comment by phansys** [comment]
Thank you @GrahamCampbell.
So, new rules must be proposed in a new version? Mean, PSR-8 by instance?

**Comment by bocharsky-bw** [comment]
PSR-8 already reserved by [Mutually Assured Hug](https://github.com/php-fig/fig-standards/blob/master/proposed/psr-8-hug/psr-8-hug.md). Maybe in later versions that will associated with **Coding Styles**

**Comment by phansys** [comment]
PSR-8 was just an example, but it means I should create a PR with a new dir inside ```proposed``` and start with my suggested definition there?

**Comment by sagikazarmark** [comment]
@GrahamCampbell it is true, currently released PSRs cannot get new rules. However I think that versioning should be introduced for PSRs, so that similar rules do not need a new standard. Autoloading was somewhat an exception, but coding style is not IMO.

**Comment by frankbardon** [comment]
@phansys: I prefer the longer versions for variable typing. I always figured it was left out to allow the developer to use whichever (s)he see's fit. Regardless, I don't see mandating a specific type hint as something that improves code readability... If that's the case then the longer word is more readable to me; it does, however, make lines shorter...

-1

**Comment by glen-84** [comment]
The title should probably be changed to include `PSR-12` instead of `PSR-2`.

`integer` and `boolean` are not valid type hints in PHP 7, so it makes sense to standardize on the shorter form.

Not to mention less to type, shorter lines, etc.

**Comment by michaelcullum** [comment]
I was intending to include this and almost forgot. Can you create an issue on cs-extended/fig-standards  please?

**Comment by samdark** [comment]
Moved to https://github.com/cs-extended/fig-standards/issues/27
