### ISSUE TITLE
How to limit the search results?

### ISSUE THREAD

**Issue by kingkarki** [php-fig/fig-standards#581]
When i search some products here in demo http://apaiio.dev.pixel-web.org/  i get few results. But when i search in my app with same library i get many results. How can i limit the results?

**Comment by kingkarki** [comment]
it would be very helpful if you will put this  http://apaiio.dev.pixel-web.org/ in git. Thanks

**Comment by bocharsky-bw** [comment]
How does your project relates to `php-fig/fig-standards` repo?

**Comment by kingkarki** [comment]
oh sorry @bocharsky-bw i posted on wrong link
