### ISSUE TITLE
[proposal] Upgrade guide 

### ISSUE THREAD

**Issue by funivan** [php-fig/fig-standards#587]
# Why
There are a lot of packages in php world. All use different format of upgrade guide. 
One developers store them in files, other in github release page or in personal websites.

Current behavior on package upgrade:
1. Find packages that you need to update
2. Find upgrade guide
3. Compare current version and next stable version
4. Read upgrade guide and check if you can safely upgrade it
5. Run upgrade
6. Fix code
 
We can remove 2,3,4 and just show `steps to execute` to perform upgrade from version A to version B    

# Pros
If package contain upgrade guide, in special format, it will be easy to upgrade your project. 
We can write plugin for composer and safely upgrade all packages that does not require any changes in code.
Even more, we can fetch upgrade steps and show them to developer according to current version and update version. 
You do not need to find all steps to upgrade from 1.0.1 to 1.0.8 you just see `steps to execute`

Thanks for reading

# Draft

Upgrade guide

# General

Upgrade file SHOULD be named `UPGRADE-GUIDE.md` and SHOULD be stored in the root of repository.
File SHOULD contain information about all stable versions upgrades. Even if upgrade does not require any steps to perform.
File can contain any alpha/beta and other unstable release upgrade information.
Upgrade sections SHOULD be represented in special order according to package versions.

# Upgrade guide file format.
* title
* description
* upgrade sections
    * name
    * description
    * step to perform
      * step description
* since information

## Title
Title SHOULD be at the top of the file

## Description
Description is optional. If you add `description` you SHOULD place it after `title`.

## Upgrade Section
Each section contain following structure `name`, `description`, `steps`, `step description`
Section SHOULD contain `name` and `steps` fields. `description` and `step description` is optional

### Section name
Section `name` SHOULD be in following format: `from {version} to {version}`

### Upgrade description
Upgrade description can contain any raw text.

### Steps
`steps` SHOULD be sorted according to priority of execution. First steps goes in top. Step start with `-` symbol
Steps format `- { step short description }\n  {step additional description}`
If upgrade do not require any changes you SHOULD also contain it in upgrade guide and write single step : `- safe upgrade`

### Step description
Optional field. Step description contain any additional information. Links, description, any custom text to help developer execute this step easier.

## Since section
Since section SHOULD be at the bottom of the file and SHOULD be in the following format `since {version}` Where `{version}` is the lowest version

# Example

```
# FileFinder upgrade guide

We use `Refactor` tool to make upgrade easier. You can download it #href and use in your project
 

## from 1.0.2 to 1.1.0
See changelist (changelist#1.1.0)
- Remove class `SearchFiles` use `Finder` instead.
    Reed more documentation about `Finder` class (docs/finder)
- Remove second argument from method `File::setContent`. Old `setContent($content, $silent=true)` new `setContent($content)`

## from 1.0.1 to 1.0.2
Upgrade is safe and do not require any changes. Just fix some bugs. See changelist (changelist#1.0.2)
- safe upgrade

since 1.0.1

```

**Comment by samdark** [comment]
I like the idea. Please post it to https://groups.google.com/forum/#!forum/php-fig

**Comment by funivan** [comment]
Done https://groups.google.com/forum/#!topic/php-fig/yIEM38VYABI

**Comment by michaelcullum** [comment]
We discuss new proposals for PSRs on the mailing list first normally. If you'd like to continue with this, please continue to discuss it there (or send it to an entrance vote if you have a coordinator and sponsor) where we can discuss it going to a potential entrance vote.
