### ISSUE TITLE
PSR docs in Firefox/IE display bullet lists incorrectly

### ISSUE THREAD

**Issue by dirtside** [php-fig/fig-standards#590]
In Kubuntu Linux 14.10, Firefox 39 (and several older versions) displays bullet lists in the PSR docs (e.g. http://www.php-fig.org/psr/psr-3/) incorrectly (see attached screenshot). Each `<li>` tag has a `<p>` child tag, which appears to cause a line break, putting the bullet point on the line above the text. Some other browsers (e.g. Chrome 43) display correctly, while yet other browsers (IE 10 on Win 8) show the same erroneous display.

I don't know whether this is a bug in Firefox/IE, or whether `<p>` tags inside an `<li>` should cause this behavior and *Chrome* is the buggy one. A proposed solution is to remove the `<p>` tags inside the `<li>` tags, since in principle they should not be necessary. Thanks!

![psr-bullets](https://cloud.githubusercontent.com/assets/5506213/8943459/e6c9c174-352f-11e5-9c70-68076a17df9e.png)

**Comment by funivan** [comment]
confirm ubuntu 14.04 firefox 39.0
