### ISSUE TITLE
[PSR-2][FR] Wrong conjugation

### ISSUE THREAD

**Issue by Geolim4** [php-fig/fig-standards#599]
The line
> Lorsqu'elles sont présentes, les déclarations abstract et final DOIVENT précédés la déclaration de la visibilité.

Must be:
> Lorsqu'elles sont présentes, les déclarations abstract et final DOIVENT précéder la déclaration de la visibilité.

**Comment by mhor** [comment]
:+1:

**Comment by samdark** [comment]
Merged. Thanks.
