### ISSUE TITLE
Private property and underscore

### ISSUE THREAD

**Issue by DenisOgr** [php-fig/fig-standards#613]
Should I use underscore in private property? When I use It catches warning: 
```bash
9 | WARNING | Property name "$_table_emails" should not be prefixed
   |         | with an underscore to indicate visibility
```
When not use underscore, it catches error:
```bash
8 | ERROR   | Private property name must be prefixed with
   |         | underscore.
```

My file: http://joxi.ru/823gkYKHxzYw2O
Result of phpcs with PSR2: http://joxi.ru/L2130BdUbwBnrX

**Comment by samdark** [comment]
4.2:

```
Property names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.
```

**Comment by DenisOgr** [comment]
@samdark, as you comment I don`t must use "single underscore to indicate protected or private". But when I don`t use I catch error "Private property must be prefixed with underscore" (you can see it on image below)

**Comment by samdark** [comment]
It means the tool you're using is wrong or you're using something other than PSR set of rules for it. It's clearly stated in the document.

**Comment by DenisOgr** [comment]
@samdark , thx. I use this library yiisoft/yii2-coding-standards + squizlabs/php_codesniffer. I call checking: vendor/bin/phpcs --standard=vendor/yiisoft/yii2-coding-standards/Yii2/,PSR2

**Comment by samdark** [comment]
Well, yes. Yii uses PSR-2 with some adjustments. You're specifying both Yii2 standard and original PSR-2.
