### ISSUE TITLE
Poor formatting of examples for PSR4.

### ISSUE THREAD

**Issue by alcohol** [php-fig/fig-standards#616]
The examples on the PSR4 page are barely readable. Please enhance the table formatting or use a list style approach. I don't know which is more feasible given the layout you are using.

**Comment by michaelcullum** [comment]
It's markdown, there's not much we can do about the way different sites render it.

**Comment by alcohol** [comment]
Well I was specifically looking at http://www.php-fig.org/psr/psr-4/. But OK :-(

**Comment by michaelcullum** [comment]
Then this issue is on the wrong repo, although I'm still not sure what can/will be done about it.

**Comment by alcohol** [comment]
Would I have to look at https://github.com/php-fig/php-fig.github.com instead?
