### ISSUE TITLE
Standard for isser / hasser naming of the class methods

### ISSUE THREAD

**Issue by bocharsky-bw** [php-fig/fig-standards#618]
Hi there!

Could we add some standard for `isser` / `hasser` for boolean values or include it to already proposed one?

I [don't find](https://github.com/php-fig/fig-standards/issues?utf8=%E2%9C%93&q=isser+) any mention about it, however accepted [PSR-7](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-7-http-message.md#34-psrhttpmessagestreaminterface) already use them.

**Comment by samdark** [comment]
What's isser / hasser?

**Comment by bocharsky-bw** [comment]
@samdark I meen class method's name, for example `isPublished()`, `isWritable()`, `hasHeader()` etc. I think it's a [generally accepted terminology](http://symfony.com/doc/current/components/property_access/introduction.html#using-hassers-issers)

**Comment by michaelcullum** [comment]
We discuss new proposals for PSRs on the mailing list first normally. If you'd like to continue with this, please suggest it on there where we can discuss it going to a potential entrance vote.

https://groups.google.com/forum/#!forum/php-fig
