### ISSUE TITLE
Proposal (PSR-8?): Authentication Interfaces

### ISSUE THREAD

**Issue by burzum** [php-fig/fig-standards#622]
Some of you might know [Opauth](https://github.com/opauth/opauth) which [has been abandoned](https://github.com/opauth/opauth/issues/81#issuecomment-131630105). This lib was a pretty nice lib as long as it was maintained.

When I was thinking about creating a new library as a successor of it I thought about PSR as well. Authentication is a pretty common process for any kind of web application. Today we have a mesh up of lots of different services that can be used to login to an application. I'm pretty sure everybody who ever had to implement more than a few of them wanted a common interface. Every SDK is pretty different, almost each response and error handling is different.

It would be awesome if a PSR standard interface could be adopted to share different authentication libs without trouble because of a common interface. Before talking or about the interface or even start designing it, is there any interest from the PSR group in defining a standard for authentication?

**Comment by michaelcullum** [comment]
This is a topic for the mailing list: https://groups.google.com/forum/?fromgroups#!forum/php-fig

Also PSR-13 is the next to be assigned (PSR-12 will be allocated in the next few hours) although I suspect PSR-13 will be version deprecation so more likely PSR-14 if this did ever get through Entrance Vote.

**Comment by michaelcullum** [comment]
If you'd like to continue with this, please suggest it on there where we can discuss it going to a potential entrance vote.

https://groups.google.com/forum/#!forum/php-fig
