### ISSUE TITLE
Coding Standard for multiple line if statements?

### ISSUE THREAD

**Issue by GreeKatrina** [php-fig/fig-standards#625]
I was wondering if you could add the coding standard for long if statements? I've seen multiple implementations regarding spacing for long if statements. From the current guide, "lines SHOULD be 80 characters or less".

```php
// Multiple lines have same indentation as "if"?
if ($long_variable_name === $also_long_variable_name 
&& $this_variable === $that_variable
&& $variable_one !== $variable_two) {
    // Do stuff
}

// Multiple lines indented 4 spaces after "if", so same line as code inside "if"?
if ($long_variable_name === $also_long_variable_name 
    && $this_variable === $that_variable
    && $variable_one !== $variable_two) {
    // Do stuff
}

// Examples for long if's with groups enclosed in parentheses would be great as well.
if (($long_variable_name === $also_long_variable_name || $foo === $bar) && 
($this_variable === $that_variable || $variable_one !== $variable_two)) {
    // Do stuff
}
// Should &&'s and ||'s separating parentheses groups start on new line? 
// They should follow whatever indentation the long if's above follow.
if (($long_variable_name === $also_long_variable_name || $foo === $bar) 
&& ($this_variable === $that_variable || $variable_one !== $variable_two)) {
    // Do stuff
}
```
I'm not limiting the options to the examples above, just providing some code to get my point across.

**Comment by ximex** [comment]
:+1:

**Comment by mwhitneysdsu** [comment]
To date, the common statement on this (at least in the GitHub issues previously opened) seems to be "don't do that". However, I tend to use the following:

```
if ($long_variable_name === $also_long_variable_name 
    && $this_variable === $that_variable
    && $variable_one !== $variable_two
) {
    // Do stuff
}

if (($long_variable_name === $also_long_variable_name || $foo === $bar) 
    && ($this_variable === $that_variable || $variable_one !== $variable_two)
) {
    // Do stuff
}
```

Essentially, 4 space indentation before the logical operator on each successive line, with the closing paren and opening brace of the if statement on a new line at the same indentation level as the `if`. Usually the second case is where I'm more likely to add some variables to shorten up the if statement, because I'm too likely to change my mind on how to handle the internal parentheses.

```
$long_variables_or_foobar = $long_variable_name === $also_long_variable_name || $foo === $bar;
$this_that_or_the_other = $this_variable === $that_variable || $variable_one !== $variable_two;
if ($long_variables_or_foobar && $this_that_or_the_other) {
    // Do stuff
}
```

**Comment by GreeKatrina** [comment]
@mwhitneysdsu Thanks for the response. 

Yeah, I definitely agree that coming across this issue is definitely a hint that your code might need some tweaking. However, there's always the legacy code excuse, ha. 

The only reason I don't typically add some variables to shorten up the if statement is because it uses memory storing more variables (although arguably not performance-changing), and I think it takes the conditions out of the conditional statement. 

If I'm doing some computing inside the conditional statement, I'll make a variable outside of it, but my personal preference is a long conditional statement compared to predefined variables and a short conditional statement.
```php
// Doing work inside statement is not good, in my opinion.
if ((floor($some_amount) + ceil($other_amount)) >= $desired_amount) {}
// Therefore, will make variable.
$compare_amount = floor($some_amount) + ceil($another_amount);
if ($compare_amount >= $desired_amount) {}
``` 

Will definitely use your first suggestion of formatting, though. I think that should be the preferred standard.

**Comment by michaelcullum** [comment]
I think this can depend on the situation and it should be left up to discretion of the developer and reviewers for a project as to what improves readability (and ability to understand the if statement which can sometimes be complex).
