### ISSUE TITLE
Additional content after closing brace on block

### ISSUE THREAD

**Issue by tpavlek** [php-fig/fig-standards#633]
In implementing coding standards for our team, something has come up. One member likes to do things like:

```php
public function doStuff()
{
    $varStuff = "gets done";
} // doStuff
```

This is something that is ambiguous in PSR-2. It does not say the closing brace for methods/class bodies MUST be the only content of the line, nor does it explicitly allow for any other content on that line.

I think this means by default it is allowable under PSR-2? Some clarity would be appreciated.

**Comment by samdark** [comment]
If it's not mentioned then it's not denied.

**Comment by tpavlek** [comment]
I assume re-opening PSR-2 for this is impossible/unweildly? I've not yet read all the bylaws, but I definitely think that having the block ending braces on their own line, without other content is a valuable rule and is the spirit of the rules I get when I read through.

**Comment by samdark** [comment]
Yes. PSRs are final once accepted.

**Comment by michaelcullum** [comment]
This could potentially be included in PSR-12

**Comment by eskrano** [comment]
if  my method called getVar i need comment //getVar ?

**Comment by dragoonis** [comment]
@tpavlek @michaelcullum @samdark the position of braces, regardless of content is to be consistent. If it's one position for one rule and another position for another rule then it's not going to be favourable.

One position to rule them all!

**Comment by samdark** [comment]
@dragoonis it's already not like that, isn't it? For anonymous function it's the same line, for classes and class methods it's next line.

**Comment by dragoonis** [comment]
@samdark I was talking about Classes and Methods. I wasn't talking about anonymous functions.

**Comment by michaelcullum** [comment]
@dragoonis This isn't about the position of the closing brace, it's about whether or not content can be appended after a closing brace.

**Comment by samdark** [comment]
@dragoonis then you're absolutely right but @michaelcullum is talking about another case.

**Comment by michaelcullum** [comment]
Added in b10e50a350aa078fabbc383c5b1b34d9d7d3688b
