### ISSUE TITLE
STuDLyCaPS should not be used for Classes in PSR-1

### ISSUE THREAD

**Issue by igorsantos07** [php-fig/fig-standards#637]
While studying PSR-1 for implementing in our company, I've noticed that actually what's usually called PascalCase or UpperCamelCase is being called "StudlyCaps" in the documentation. Actually, [studly caps](https://en.wikipedia.org/wiki/Studly_caps) is more like a messy caps than camel-cased words.

I wonder if it would clarify if the reference was about [PascalCase](https://en.wikipedia.org/wiki/CamelCase) (namely, see the second paragraph) instead?

> Studly caps is a form of text notation in which the capitalization of letters varies by some pattern, or arbitrarily, usually also omitting spaces between words and often omitting some letters, for example, StUdLyCaPs or STuDLyCaPS.

**Comment by ximex** [comment]
:+1:

**Comment by michaelcullum** [comment]
This is something worth looking at as a clarification but I'd rather not break BC either.

@keradus How does CS fixer interpret "StudlyCaps"?

**Comment by keradus** [comment]
for us it's alias for camelCase/PascalCase

**Comment by keradus** [comment]
:+1: for clarification ! I think the PascalCase was intended in PSR

**Comment by igorsantos07** [comment]
Precisely. It's a matter of understanding and wording, simply. It's not a
real change to the PST, but instead the meaning of StudlyCaps is actually
different from what's intended in the PSR.

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by michaelcullum** [comment]
@keradus I agree I think that was the intention (@pmjones). I'm :+1: to changing that (and add a link to explain the terminology in the meta doc).

**Comment by michaelcullum** [comment]
Complete in a9a3d3158a0cbe1f2745fa8d6d5004a4d8a748b8
