### ISSUE TITLE
[PSR-2] [PSR-12] optional new line before class closing bracket

### ISSUE THREAD

**Issue by davrek** [php-fig/fig-standards#647]
[PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) states in 4.1
> the closing brace for the class MUST go on the next line after the body.

I would suggest to make this optional for the following reasons:

1. There is no such restriction for after the opening bracket of a class.
2. It allows to determine the method scope more easily, i.e. each function can have an empty line before and after its definition.
3. Whenever you add a method, you can just navigate anywhere on the line between the last method's closing bracket and the class's closing bracket.

**Comment by michaelcullum** [comment]
Hi David,

To quote the full line "The opening brace for the class MUST go on its own
line; the closing brace for the class MUST go on the next line after the
body."

I think the intention here is that the opening brace must be on its own
line which should be the preceding line after the closing parenthesis as a
blank line there would just be odd. (Point 1)

I think it is fairly obvious at the end of the last method in a class due
to the repeated closing braces and indentation and a blank line after the
last method would just be un-nessasary. (Point 2)

I'm not sure what you mean regarding point 3.

I doubt there will be much support for this change however we can add a
clarification for the opening brace as described.

--
Thanks,
Michael Cullum

**Comment by davrek** [comment]
Hi Michael,

> I think the intention here is that the opening brace must be on its own line which should be the preceding line after the closing parenthesis as a blank line there would just be odd. (Point 1)

If you haven't mistakenly written opening brace instead of closing brace, I don't understand what you mean here (sorry, not a native speaker). The oddity is in the eye of the beholder, I regard it as odd not to have an empty line to separate the method body from the class's closing bracket.

> I think it is fairly obvious at the end of the last method in a class due to the repeated closing braces and indentation and a blank line after the last method would just be un-nessasary. (Point 2)

It may be obvious as in you can't misread it, but it still makes a visual difference to have all methods framed by an empty line as opposed to all but the last method.

Let's examine an example for a better visualization and understanding:

**PSR-2**
```php
class MyClass
{
    /**
    * @var string
    */
    private $someValue;

    /**
    * This method does something.
    */
    public function doOneThing()
    {
        // ...
    }

    /**
    * This method does something else.
    */
    public function doSomethingElse()
    {
        // ...
    }
}
```

I don't recall PSR-2 saying anything about an empty line after the class's opening bracket, so you may as well have one or not. I think this is inconsistent. If you may not put an empty line before the closing bracket of a class, why is it optional after the opening bracket?

**proposed variant**
```php
class MyClass
{

    /**
    * @var string
    */
    private $someValue;

    /**
    * This method does something.
    */
    public function doOneThing()
    {
        // ...
    }

    /**
    * This method does something else.
    */
    public function doSomethingElse()
    {
        // ...
    }

}
```

The difference is subtle, but to me, it makes more sense to have each method separated by empty lines instead of the last one bein glued to the closing bracket.

And here you may see what I meant at 3.: you have twice the space to click to navigate after the last method, i.e. on the line with the method's closing bracket or on the empty line, which is more error resistant and thus faster.

My conclusion is that either an empty line after the class's opening bracket should equally not be allowed or - what I prefer - an empty line before the class's closing bracket should be possible.

**Comment by michaelcullum** [comment]
I'm personally against this. It's breaking BC with PSR-2 for something
rather unnecessary and I'm against the use of SHOULD or removing conditions
from PSR-2 for the reasons stated by Matthew last year (Briefly described
in https://mwop.net/blog/2013-02-27-resigned-from-php-fig.html).

If there is a significant amount of support then we can revisit this but
otherwise...

--
Michael C

**Comment by davrek** [comment]
I know PSR-2 won't be changed, that's fine. I just want to seize the opportunity during formation of PSR-12 to address this issue as it's not consistent regarding line after opening bracket and before closing bracket of a class.
AFAIK, it's also not defined, whether there can/should/must be an empty line between the php opening tags and the namespace. I could live with a definitive statement on these two points in PSR-12, but would prefer both to stay optional and, for consistency, let the empty line between class body and closing bracket be optional as well.

**Comment by michaelcullum** [comment]
I never talked about changing PSR-2, but we want to have as smooth a migration path as possible from PSR-2 to PSR-12 and I've never seen the CS you're describing in a big project (Not saying it doesn't happen, it's just not common, never mind mainstream).

I'll add a statement to PSR-12 to clarify that there shouldn't be a blank line before closing braces, or after opening braces so that is is clarified in accordance with what is most common.

`it's also not defined, whether there can/should/must be an empty line between the php opening tags and the namespace` This is all changing due to the inclusion of `define(strict_types=1);` anyway and that's all already been done.

**Comment by keradus** [comment]
:-1: for adding such exception to rule

**Comment by michaelcullum** [comment]
Fixed in https://github.com/cs-extended/fig-standards/commit/88bb52be0fbeb3f04297b7d78af329d611f36c05

**Comment by davrek** [comment]
Thank you for the clarification. I'm happy with it being unambiguous if this is widely accepted standard.
