### ISSUE TITLE
Namespace for Tests

### ISSUE THREAD

**Issue by pauloelr** [php-fig/fig-standards#652]
Hello,

I was doing some research and talking with some members of my PHP User Group and I noticed an inconsistency in how major frameworks name their tests namespace, considereing a class named ´\Foo\Bar\Baz´ I've encountered several ways they are doing it:

1 - \Foo\Bar\BazTest (Respect)
2 - \FooTest\Bar\BazTest (Zend Framework 2)
3 - \Foo\Test\Bar\BazTest 
4 - \Foo\BarTest\BazTest
5 - \Foo\Bar\Test\BazTest (Symfony)
6 - \BazTest (Laravel)

CakePHP do it another way it stores the test cases in `\Foo\Test\TestCase\Bar\BazTest`
And test fixtures on `\Foo\Test\Fixture\Bar\BazTest`

There is also a question on StackOverflow (http://stackoverflow.com/questions/12117254/organizing-phpunit-tests-in-namespaces) discussing this exactly subject

So I'm wondering if it's not a case that requires standardization?
If there was a standard in that matter it will be much more simple to locate tests for each class
Tools for test analyses and code coverage could also beneficiate from this

**Comment by michaelcullum** [comment]
This belong on the mailing list where you're welcome to raise but I'd add that I'm :-1: to having this in PSR-12.

Thanks
