### ISSUE TITLE
[PSR-2] Question about function signatures with return types.

### ISSUE THREAD

**Issue by naroga** [php-fig/fig-standards#658]
PSR2 dictates:

> There must be a single space between the closing parenthesis and the opening brace of a multi-line function declaration.

However, since PHP 7.0 introduced return types for functions, the following function has been found to be in violation of that rule (as pointed by PHP_Codesniffer):

    public function myFunction(
        $param1,
        $param2,
        $param3,
        $param4,
        $param5,
    ) : SomeClass {

I couldn't find a single way to add a return type to that multiline function and not be in violation of PSR2. My linter has gone crazy, and my OCD won't let me commit things to my repository, because I want my code to be strictly typed and I want it to be PSR2 compliant.

How do I make this function signature compliant with PSR2 without removing the return type? I'll fix my linter when I know what to do.

**Comment by michaelcullum** [comment]
PSR-12 will detail how to handle PHP 7 functionality.

It's up to @keradus and the PHP CS team as to how they want to handle PHP 7 code when PSR-2, not PSR-12 is specified. Although my personal recommendation would be to allow anything with type hinting, but always ensure the parentheses are on a different line to the curly brace.

Details about how we do this in PSR-12: https://github.com/cs-extended/fig-standards/issues/9

As this isn't a fixable issue by us @samdark could this be closed please?

**Comment by keradus** [comment]
@michaelcullum 
`PHP Code Snifer` mentioned by @naroga is different tool than `PHP CS Fixer`.
Later one will make no changes with that typehinting when using fixers from PSR2. When CS for PHP7 will be accepted then PHP CS Fixer will have separate level for it too!

**Comment by michaelcullum** [comment]
@keradus Ah I do apologise.

@gsherwood it appears is the largest contributor to PHP Code Sniffer and I assume the project lead? As a general note, your feedback on PSR-12 would also be most welcome.

**Comment by gsherwood** [comment]
@naroga I'm just about to release a new PHPCS/PHPCBF version with return type support (you may be noticing other bugs already). Before I do, I'll change this sniff to validate that there is one space after `(` and one space before '}'. This will almost always be the same space character before PHP7, so I'll make sure only one error is generated.

@michaelcullum 
> Although my personal recommendation would be to allow anything with type hinting, but always ensure the parentheses are on a different line to the curly brace.

This is a multi-line declaration, so the part of PSR-2 that applies is:
> When the argument list is split across multiple lines, the closing parenthesis and opening brace MUST be placed together on their own line with one space between them.

So I can't change PHPCS to enforce a newline or to be silent when one is used for multi-line declarations. But of course this is already valid (including line length in this specific case), which might have been what you were referring to:
```php
public function myFunction($param1, $param2, $param3, $param4, $param5) : SomeClass
{
}
```

**Comment by gsherwood** [comment]
> I'll change this sniff to validate that there is one space after ( and one space before '}'.

Actually, it probably makes more sense to just check for a single space before the '}'. In the absence of any guidance from the PSR, it's probably best to stick with the format used in the docs.

**Comment by naroga** [comment]
Thank you @gsherwood.

Thank you everyone that took their time to pitch in.
