### ISSUE TITLE
requirements of translation?

### ISSUE THREAD

**Issue by jhdxr** [php-fig/fig-standards#666]
Hello, I'm one of the translators of php doc, and I'd like to translate these standards into Chinese, however I have not found any requirements or guide about contributing translation.

**Comment by samdark** [comment]
Submit a pull request then get more native speakers to review it and comment that it's OK to merge.

**Comment by geekmichael** [comment]
Count me in.

Kind Regards,
Michael ZHANG

**Comment by gaomd** [comment]
@jhdxr @geekmichael We already have enough Chinese pull requests opened at this time (search pull requests for a complete list of Chinese translations), I think we'd better figure out an way to merge existing PRs instead of re-translate the wheel.

**Comment by samdark** [comment]
In order to merge existing ones I need confirmation/review from more people. Review existing ones and either comment "it could be merged" or comment inline about mistakes. That would really help. Thanks!
