### ISSUE TITLE
[proposal] ORM Interfaces

### ISSUE THREAD

**Issue by psfpro** [php-fig/fig-standards#671]
What do you think about the adoption of the common ORM interfaces?
For example look like a this:
http://www.doctrine-project.org/about.html
```php
<?php

interface ObjectManagerInterface
{
    public function find($className, $id);
    public function persist($object);
    public function remove($object);
    public function merge($object);
    public function clear($objectName = null);
    public function detach($object);
    public function refresh($object);
    public function flush();
    public function getRepository($className);
}

interface ObjectRepositoryInterface
{
    public function find($id);
    public function findAll();
    public function findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null);
    public function findOneBy(array $criteria);
}
```
Then we can use
```php
class Component
{
    /**
     * @var ObjectManagerInterface
     */
    protected $objectManager;

    /**
     * @param ObjectManagerInterface $objectManager
     */
    public function __construct(ObjectManagerInterface $objectManager)
    {
        $this->objectManager = $objectManager;
    }

    public function createProduct()
    {
        $product = new Product();
        $product->setName('ProductName');
        $this->objectManager->persist($product);
        $this->objectManager->flush();
    }
}
```
So I can create a component and then choose ORM.
You can take a Doctrine or MyOwnSuperORM.
You can configure components by dependency injection.
You could use this component for Yii, Symfony, Zend if a single interface ORM. Currently have to create for each platform separately.

**Comment by samdark** [comment]
I think frameworks may benefit from it. Please post to the mailing list: https://groups.google.com/forum/#!forum/php-fig

**Comment by DavidBadura** [comment]
:+1: for this!

**Comment by psfpro** [comment]
New topic created
https://groups.google.com/forum/#!topic/php-fig/ADNU2mQAHRk

**Comment by ousamabenyounes** [comment]
:+1:  for this !

**Comment by Ocramius** [comment]
:-1: for this (at the moment):

 - this assumes that your ORM is UnitOfWork based - that is not necessarily always the case
 - we (doctrine project) are currently in the process of designing ORM 3.x, so we don't yet know what sort of interfaces and APIs will be discovered in this process - introducing these interfaces now will simply restrict our research freedom - these interfaces are currently extracted from `doctrine/common`, which is not necessarily what ORM libraries want to emulate
 - these interfaces ([`ObjectManager`](https://github.com/doctrine/common/blob/79fdef35a79a3694e5ae552575d23fd7dc8482c2/lib/Doctrine/Common/Persistence/ObjectManager.php) and [`ObjectRepository`](https://github.com/doctrine/common/blob/79fdef35a79a3694e5ae552575d23fd7dc8482c2/lib/Doctrine/Common/Persistence/ObjectRepository.php)) already exist under [`doctrine/common`](https://packagist.org/packages/doctrine/common), which is probably one of the [most installed packagist packages out there](https://www.versioneye.com/php/doctrine:common/references)

I don't think that we are ready for standardizing this yet.

**Comment by gianarb** [comment]
The first question is "why should we standardize ORM implementations?"

**Comment by psfpro** [comment]
The implementation will be different, the interface is unified. The interfaces are shown for example only.

**Comment by Ocramius** [comment]
> The interfaces are shown for example only.

That's my main concern - we are far from getting a stable interface (that will last for some years)

**Comment by samdark** [comment]
We at Yii are adjusting DBAL interfaces as well in major versions and still haven't found perfect one. So yes, in this regard we have no perfect solution that is confirmed to work flawlessly.

**Comment by psfpro** [comment]
It is understandable that you can't just go and create a unified interface. We need to understand it the right way or not.

**Comment by kayladnls** [comment]
Agree with @Ocramius here. 

Also, this wouldn't address AC pattern ORMs, so if/when it became a standard I think it should be more descriptively named to what it is.

**Comment by taylorotwell** [comment]
:-1:

**Comment by samdark** [comment]
OK. I guess the idea will fail the enterance vote. At least in its current form.

**Comment by psfpro** [comment]
Time will show the path of development.

**Comment by samdark** [comment]
Well, initial idea should be shaped before attempting it again i.e. which type of ORM to make interface for etc.
