### ISSUE TITLE
Configuration Repository PSR opinion?

### ISSUE THREAD

**Issue by leemason** [php-fig/fig-standards#677]
Im working a few packages, all of which need configurations (as does everybody elses).

should we consider a psr for application configuration?

i have this so far: https://github.com/conformity/config-recommendation

Very similar to the container spec, but for configuration.

It makes no assumptions about the storage layer, thats down to the implementation. but the psr in my opinion should provide:

```php
get($key);

set($key, $value);

has($key);

setEnvironment($env);
```

functions as its most basic level. (in my option the symfony config is great at what it does, but a huge beast and not really required for most use cases).

also alot of config repositories implement arrayaccess, but some others dont so i havent added this as it should be optional.

I think it may also benefit from the container->delagates functionality for loading from different sources (env, json, array, yml, xml, etc), but havent included this yet as i want to get a feel for peoples opinions first.

how does that sound?

**Comment by samdark** [comment]
Please discuss it in mailing list: https://groups.google.com/forum/#!forum/php-fig
