### ISSUE TITLE
[PSR-7] RequestInterface::withUri()

### ISSUE THREAD

**Issue by peterr** [php-fig/fig-standards#678]
http://www.php-fig.org/psr/psr-7/#host-header gives us the following table:

Request Host header<sup>[1](#rhh)</sup> | Request host component<sup>[2](#rhc)</sup> | URI host component<sup>[3](#uhc)</sup> | Result
----------------------------------------|--------------------------------------------|----------------------------------------|--------
''                                      | ''                                         | ''                                     | ''
''                                      | foo.com                                    | ''                                     | foo.com
''                                      | foo.com                                    | bar.com                                | foo.com
foo.com                                 | ''                                         | bar.com                                | foo.com
foo.com                                 | bar.com                                    | baz.com                                | foo.com

- <sup id="rhh">1</sup> `Host` header value prior to operation.
- <sup id="rhc">2</sup> Host component of the URI composed in the request prior
  to the operation.
- <sup id="uhc">3</sup> Host component of the URI being injected via
  `withUri()`.

Are the results in the second and third row correct? In my opinion the result for the second row should be an empty string (instead of `foo.com`), and for the thrid `bar.com` (instead of `foo.com`), according to the following fragment of the annotation from RequestInterface::withUri():

```php
* You can opt-in to preserving the original state of the Host header by
* setting `$preserveHost` to `true`. When `$preserveHost` is set to
* `true`, this method interacts with the Host header in the following ways:
*
* - If the the Host header is missing or empty, and the new URI contains
*   a host component, this method MUST update the Host header in the returned
*   request.
* - If the Host header is missing or empty, and the new URI does not contain a
*   host component, this method MUST NOT update the Host header in the returned
*   request.
*   - If a Host header is present and non-empty, this method MUST NOT update
*   the Host header in the returned request.
```

**Comment by michaelcullum** [comment]
The spec is finalised but should you believe this is a typo/formatting issue or worthy of errata, please post it to the mailing list.
