### ISSUE TITLE
Slovak translation of accepted PSR

### ISSUE THREAD

**Issue by skecskes** [php-fig/fig-standards#680]
Hi,

I started to work on **Slovak translation** of **accepted PSRs** - https://github.com/skecskes/fig-standards/tree/master/accepted/sk 
If anybody has time, *please review* it to check errors or you can also *help by translating*.
When it's all done and checked, I will pull request to submit it here.

Thanks.

**Comment by michaelcullum** [comment]
Please send a pull request, then people can review it.
