### ISSUE TITLE
[PSR-12] Indention and Whitespaces

### ISSUE THREAD

**Issue by MarkusRodler** [php-fig/fig-standards#684]
In the upcoming version of PHP 7.0 it is possible to declare strict_types and return types. But in the current version of PSR-12 is no definition on how these things should be written. It is only covered in the example but without any rule. 

Examples: 
- Should the declare declaration on a new line or should it be on the same line as the <?php tag.
``` php
<?php
declare(strict_types=1);
// or
<?php declare(strict_types=1);
```
- Should there be no whitespaces between the strict_type, the equals and the 1 on the declare declaration declare(strict_types=1); or would it be more consistent with the other equals in e.g. if-statements: declare(strict_types = 1);
``` php
<?php
declare(strict_types = 1);
// or
<?php 
declare(strict_types=1);
```
- The same applies to the new return type declarations. should there be no whitespace before the colon and one after the colon or would this way more consistent: 
``` php
public function sampleFunction(int $a, int $b = null) : array
// or
public function sampleFunction(int $a, int $b = null): array
// or
public function sampleFunction(int $a, int $b = null) : array
// or
public function sampleFunction(int $a, int $b = null) :array
// or 
public function sampleFunction(int $a, int $b = null):array
```
My suggestion would be to stick with the first ones of each example, but for me it is even more important to have rules for this. No rules means dozens of combinations :(

P.S.: I dont't know if this is the right place to ask. So if it's not correct, please show me the right direction to handle such requests.

**Comment by samdark** [comment]
The right place to ask is mailing list: https://groups.google.com/forum/#!forum/php-fig
