### ISSUE TITLE
[PSR-12] Don't require an initial blank line

### ISSUE THREAD

**Issue by Synchro** [php-fig/fig-standards#689]
Section 3 says:
 > When no declare declarations are present there MUST be a blank line after the opening <?php tag.

That's really pointless, just a waste of space. As testament to this, notice that this rule is contravened by almost every example in the doc!

Personally I would expect the first thing after an initial opening php tag to be a file-level docblock.

**Comment by samdark** [comment]
Please post to https://groups.google.com/forum/#!forum/php-fig. Thanks!
