### ISSUE TITLE
PSR-6's exceptions interfaces, PSR-3's exceptions classes

### ISSUE THREAD

**Issue by aequasi** [php-fig/fig-standards#694]
https://github.com/php-fig/log/blob/master/Psr/Log/InvalidArgumentException.php

vs

https://github.com/php-fig/cache/blob/master/CacheException.php
https://github.com/php-fig/cache/blob/master/InvalidArgumentException.php

Also, log doesn't have a LoggerException.

**Comment by aequasi** [comment]
Also, PSR-6's interfaces for exceptions are not suffixed with `Interface`, which is required by the by-laws

**Comment by aequasi** [comment]
Sorry that i wasn't able to review this earlier

**Comment by samdark** [comment]
Please post that to mailing list.
