### ISSUE TITLE
[PSR-6] How to save cache item without CacheItemInterface::getExpiration

### ISSUE THREAD

**Issue by Nyholm** [php-fig/fig-standards#696]
I have seen the #604 PR when we removed `CacheItemInterface::getExpiration`. @Crell made a reference to a discussion [in the mailing list](https://groups.google.com/forum/#!searchin/php-fig/getExpiration/php-fig/vbG1DcchdjI/Y3b546PoCwAJ).

How should I implement the `CachePoolItemInterface::save` function without this method?

I could do like this to store the object in cache forever. But that will fill my cache with objects that are stale and should not be used. It does not seam like a good idea...
```php
public function save(CacheItemInterface $item)
{
    return apc_store($item->getKey(), $item);
}
```

Am I missing something? What is the suggested implementation?

**Comment by samdark** [comment]
Please use mailing list for discussions. Thanks.
