### ISSUE TITLE
Move PSR 6 from proposed to accepted.

### ISSUE THREAD

**Issue by saji89** [php-fig/fig-standards#704]
PSR 6 has passed the acceptance vote:
https://groups.google.com/forum/#!msg/php-fig/dSw5IhpKJ1g/WqITQoNACAAJ

So, please move it from `proposed` to `accepted`.

Also, the PSR website needs to be updated: http://www.php-fig.org/psr/

**Comment by Crell** [comment]
PR is opened: https://github.com/php-fig/fig-standards/pull/708
