### ISSUE TITLE
PSR-6: Error in cache-meta.md

### ISSUE THREAD

**Issue by beberlei** [php-fig/fig-standards#706]
It mentions a call to `$item->set('value', 3600);`. It should probably be

    $item->set('value');
    $item->expiresIn(3600);

**Comment by michaelcullum** [comment]
@Crell @dragoonis

**Comment by dragoonis** [comment]
Waiting for @Crell to handle this.

**Comment by Crell** [comment]
I added a commit for this in https://github.com/php-fig/fig-standards/pull/708.
