### ISSUE TITLE
[coding style] Standard to mark deprecated classes 

### ISSUE THREAD

**Issue by mvar** [php-fig/fig-standards#714]
Newer Symfony versions introduced nice feature - error triggering for deprecated classes. I think this is VERY useful for end user. When user tries to use class, immediately gets error that this class is deprecated. See example below.

```php
<?php

namespace Foo;

@trigger_error(
    'The XXX class is deprecated and will be removed in 2.0. Use YYY instead.',
    E_USER_DEPRECATED
);

use Bar\YYY;

/**
 * @deprecated Will be removed in 2.0. Use the YYY instead.
 */
class XXX extends YYY
{
}
```

This file-level error triggering is so great because you can get "deprecated" message even when you don't call any method from that class.

The only problem is that source code given above does not comply PSR2:

> A file should declare new symbols (classes, functions, constants, etc.) and cause no other side effects, or it should execute logic with side effects, but should not do both.

What if we add special rule/exception for this "deprecated" case?

**Comment by samdark** [comment]
I'm not seeing any profit in triggering it runtime. We have `@deprecated` marks in phpdoc and any IDE can give you a list of what's using these deprecated methods and classes.

**Comment by GrahamCampbell** [comment]
Your code there violates PSR-2. Yeh.

**Comment by GrahamCampbell** [comment]
Maybe better to trigger the error in the constructor, unless of course, the class is full of static methods and never gets instantiated.

**Comment by GrahamCampbell** [comment]
I don't think we should make an exception here. There are good reasons why PSR-2 has that rule. For example, to not mess up code coverage generation, or interferer with class preloading or phar building.

**Comment by mvar** [comment]
`@deprecated` annotation is nice for IDE, but it's not that simple to get all usages of deprecated classes/methods. Sometimes you can have your deprecated class/method name in variable, sometimes logic can be executed through magic method, etc.

Why to put "deprecated" error in file level? As I said, that allows you to get errors without initializing the class or calling it's methods. Few examples:

- Checking if class exists triggers error
- Calling class' constant triggers error

I don't know how no one used this before. This is the right usage. If you deprecated class - warn developer despite what was used (initialization, static method, constant). That's similar to PHP's behaviour. You called something deprecated - you get error.

I'm against exceptions too, but not always good things follows pattern.

**Comment by GrahamCampbell** [comment]
Yeh. It seems we're between a rock and a hard place, lol.

**Comment by mvar** [comment]
Any comments from real contributors?

**Comment by samdark** [comment]
I don't really like enforcing it runtime and strongly prefer it handled by IDEs and static analyzers.

**Comment by GrahamCampbell** [comment]
Maybe this isn't something that actually needs to be defined by PSR, or, if anything, just inferred by PSR-5?

**Comment by samdark** [comment]
I prefer to close this discussion. Issues are to be removed anyway soon so if you want to discuss it further, let's get to mailing list: https://groups.google.com/forum/#!forum/php-fig
