### ISSUE TITLE
Short tags <? widget(); ?> on psr-1

### ISSUE THREAD

**Issue by 8kb** [php-fig/fig-standards#725]
Now 2016 year.
php7.0.1 released.
Short tags work on 5.4+ by default.

http://www.php-fig.org/psr/psr-1/#2-1-php-tags
PHP code MUST use the long <?php ?> tags or the short-echo <?= ?> tags; it MUST NOT use the other tag variations.

Why?

**Comment by samdark** [comment]
Wrong. Short echo works but short tags do not.

**Comment by 8kb** [comment]
Alexander,
short_open_tag Default="1"

**Comment by samdark** [comment]
Yes but it's often turned off and to achieve maximum compatibiltiy it's recommended to use `<?php`. `<?=` can't be turned off therefore it's recommended to use it all the time.
