### ISSUE TITLE
Missing closing bracket on  "The Coding Guidelines on One Page" pdf

### ISSUE THREAD

**Issue by endder** [php-fig/fig-standards#736]
Hi All, I don't no if this is the right place to post this, but there is a missing closing bracket on the IF statement, in the "The Coding Guidelines on One Page" pdf.

http://flowframework.readthedocs.org/en/stable/_downloads/TYPO3_Flow_Coding_Guidelines_on_one_page.pdf

**Comment by michaelcullum** [comment]
This is the FIG repo, you want to speak to the typo3 guys about that.
