### ISSUE TITLE
[PSR-12] Cover insteadof and as

### ISSUE THREAD

**Issue by samdark** [php-fig/fig-standards#738]
The [`insteadof`](http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict) and [`as`](http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.visibility) operators for using trait are not covered.

**Comment by michaelcullum** [comment]
Can we not use issues on this repo as we'll be turning them off quite soon? You can always use https://github.com/cs-extended/fig-standards/issues for PSR-12 issues so they don't get lost.

**Comment by samdark** [comment]
I'm tagging these so it's easy to find: https://github.com/php-fig/fig-standards/labels/Coding%20Standards

**Comment by samdark** [comment]
Wait, are we going to turn off issues on the whole repo? I though it's about translations only...

**Comment by samdark** [comment]
I can move all the issues to another repo, not a big problem.

**Comment by michaelcullum** [comment]
Yeah. Issues get lost on here all the time and don't get spotted by PSR editors which is problematic. It was agreed on the ML (before I even mentioned translations) to turn off issues

**Comment by samdark** [comment]
Personally things on ML are getting lost for me much easier. I love old good forums instead but we have what we have. Will move issues away then this week.

**Comment by samdark** [comment]
Moved to https://github.com/cs-extended/fig-standards/issues/26
