### ISSUE TITLE
[PSR-12] Bracketed syntax for namespaces

### ISSUE THREAD

**Issue by samdark** [php-fig/fig-standards#739]
```php
namespace Acme;

class Foo
{
}
```

vs

```php
namespace Acme
{
    class Foo
    {
    }
} 
```

**Comment by zelenin** [comment]
I vote for first variant.

**Comment by michaelcullum** [comment]
Sometimes you want to do something like https://github.com/ircmaxell/password_compat/blob/master/lib/password.php#L10 though so :-1: for inclusion if this in PSR-12.

**Comment by samdark** [comment]
What's the idea behind that?

**Comment by zelenin** [comment]
@michaelcullum your namespace is root by default. ```namespace { .. }``` is overhead there I think.

**Comment by ircmaxell** [comment]
@samdark and @zelenin look further down in the file. There's another namespace further down.

Basically, if you ever need to use more than one namespace in a file, you need to use brace style. That's why PHP supports both syntaxes. 

Instead, what I'd prefer to see is a standard that says "only use brace syntax if you use more than one namespace in a file". or something like that. But explicitly disallowing it is not good...

**Comment by zelenin** [comment]
@ircmaxell more than one namespaces in a file not works with PSR-4, I think.

**Comment by michaelcullum** [comment]
@zelenin PSR-0 or PSR-4 compliance is not required by PSR-12.

**Comment by zelenin** [comment]
@michaelcullum You're right. But it must not conflict with it too. If we don't recommend the variant  without brackets, it means we don't recommend any variant.

**Comment by michaelcullum** [comment]
Saying "Namespace brace syntax MUST NOT be used unless you have multiple namespaces in one file' doesn't say multiple namespaces in one file are allowed. Also you can restrict something in PSR-4 that is allowed in PSR-12 (That's how specs work together, each one introduces further requirements on different things). Further restriction vs conflicting statements. The only conflicting statement would be if we said 'You must have more than one namespace in a file' which of course we'd never do.

**Comment by samdark** [comment]
Moved to https://github.com/cs-extended/fig-standards/issues/25.
