### ISSUE TITLE
Is type casting documented? Where?

### ISSUE THREAD

**Issue by hrvoj3e** [php-fig/fig-standards#742]
Which is correct?

(space after casting) : There MUST be one space after the control structure keyword
```php
$number = (int) $_GET['number'];
```
(without space)
```php
$number = (int)$_GET['number'];
```

I am referring to:
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#5-control-structures

**Comment by michaelcullum** [comment]
PSR-2 is final but this could be a candidate for PSR-12. Feel free to suggest this on the mailing list or on cs-extended/fig-standards

**Comment by samdark** [comment]
@hrvoj3e please create issue at repository @michaelcullum linked to. Thanks!

**Comment by hrvoj3e** [comment]
I have!
https://github.com/cs-extended/fig-standards/issues/29

**Comment by samdark** [comment]
Thanks!
