### ISSUE TITLE
[PSR-2] PHP7 namespace grouping?

### ISSUE THREAD

**Issue by kleijnweb** [php-fig/fig-standards#743]
Has any thought been put into a standard for the namespace grouping sugar in PHP 7.0?

As is, phpcs will (correctly) accept neither of these:

```php
use KleijnWeb\SwaggerBundle\Exception\{
    MalformedContentException,
    UnsupportedContentTypeException
};
```

```php
use KleijnWeb\SwaggerBundle\Exception\{MalformedContentException, UnsupportedContentTypeException};
```

Both dramatically improve readability IMHO.

**Comment by michaelcullum** [comment]
Yes. This is in PSR-12.

**Comment by kleijnweb** [comment]
Thanks, found it. Not that ubiquitous yet, so I hope you'll forgive my ignorance. I don't suppose anyone has conjured up a phpcs ruleset? Google letting me down. Much appreciated.

**Comment by michaelcullum** [comment]
Not just yet no
